import { AppError } from "../../shared/src/index";
import { containerArgs } from "./policy";
import type { OwnedResource } from "./owned-resources";
export type Probe={uid:number;gid:number;noNewPrivs:number;seccomp:number;memoryMax:number;swapMax:number;pidsMax:number;cpuQuota:number;cpuPeriod:number;oomKills:number;workspace:{bytes:number;inodes:number;nodev:boolean;nosuid:boolean};tmp:{bytes:number;inodes:number;nodev:boolean;nosuid:boolean;noexec:boolean};rootReadonly:boolean;pids:Record<string,string>;selfPid:number};
const deny=()=>new AppError("SANDBOX_UNAVAILABLE","无法证明容器资源限制及环境隔离");
export function assertIsolation(record:OwnedResource,container:any,probe:unknown):asserts probe is Probe {
  const p=probe as Probe|undefined,h=container?.HostConfig,c=container?.Config;
  const expected=containerArgs(record.imageId,record.token),tmpfs=expected.flatMap((arg,i)=>arg==="--tmpfs"?[expected[i+1]]:[]),env=expected.flatMap((arg,i)=>arg==="--env"?[expected[i+1]]:[]);
  const actualEnv=c?.Env,publicKeys=["NODE_VERSION","YARN_VERSION"];
  if(container?.Id!==record.containerId||container.Name!==`/fastgpt-${record.token}`||container.Image!==record.imageId||container.State?.Running!==true||c?.Labels?.["org.fastgpt.desktop.owner"]!==record.token||c.User!=="1000:1000"||c.WorkingDir!=="/workspace"||!Array.isArray(actualEnv)||actualEnv.length>env.length+2||new Set(actualEnv.map((e:string)=>e.split("=",1)[0])).size!==actualEnv.length||env.some(e=>!actualEnv.includes(e))||actualEnv.some((e:unknown)=>typeof e!=="string"||e.includes("\0")||e.length>8192||!env.includes(e)&&!publicKeys.includes(e.split("=",1)[0])))throw deny();
  if(!h||h.NetworkMode!=="none"||h.ReadonlyRootfs!==true||h.Privileged!==false||h.Memory!==1073741824||h.MemorySwap!==1073741824||h.PidsLimit!==128||h.NanoCpus!==2000000000||h.CgroupnsMode!=="private"||h.IpcMode!=="private"||h.PidMode!==""||h.Init!==true||h.LogConfig?.Type!=="none"||JSON.stringify(h.CapDrop)!=='["ALL"]'||h.CapAdd?.length||!Array.isArray(h.SecurityOpt)||!h.SecurityOpt.includes("no-new-privileges:true")||h.SecurityOpt.some((s:string)=>s!=="no-new-privileges:true")||h.Binds?.length||h.Devices?.length||h.DeviceRequests?.length||h.PublishAllPorts||Object.keys(h.PortBindings??{}).length||container.Mounts?.length||Object.keys(h.Tmpfs??{}).length!==2||tmpfs.some(t=>{const cut=t.indexOf(":");return h.Tmpfs[t.slice(0,cut)]!==t.slice(cut+1);}))throw deny();
  if(!p||p.uid!==1000||p.gid!==1000||p.noNewPrivs!==1||p.seccomp!==2||p.memoryMax!==1073741824||p.swapMax!==0||p.pidsMax!==128||p.cpuQuota!==2*p.cpuPeriod||!Number.isInteger(p.cpuPeriod)||p.cpuPeriod<=0||!Number.isSafeInteger(p.oomKills)||p.oomKills<0||p.workspace?.bytes!==1073741824||p.workspace.inodes!==16384||p.workspace.nodev!==true||p.workspace.nosuid!==true||p.tmp?.bytes!==67108864||p.tmp.inodes!==4096||p.tmp.nodev!==true||p.tmp.nosuid!==true||p.tmp.noexec!==true||p.rootReadonly!==true||!p.pids||typeof p.pids!=="object"||Object.keys(p.pids).length>128||Object.entries(p.pids).some(([pid,start])=>!/^\d+$/.test(pid)||typeof start!=="string"||!/^\d+$/.test(start))||!Number.isInteger(p.selfPid)||p.selfPid<1)throw deny();
}
export function assertQuiescent(before:Probe,after:Probe){if(Object.entries(after.pids).some(([pid,start])=>Number(pid)!==after.selfPid&&before.pids[pid]!==start))throw new AppError("SANDBOX_UNAVAILABLE","命令后台进程未完成清理");}
