import { useEffect,useState } from "react";
import type { WorkspacePreview,ExportPreview,ExportResult,BackupView } from "../../../../../packages/shared/src/index";
import { useWorkspace } from "../hooks/useWorkspace";
import { WorkspaceDiff } from "./WorkspaceDiff";
import { ExportDialog } from "./ExportDialog";
const status={written:"已写入",deleted:"已删除",skipped:"已跳过",conflict:"冲突，未覆盖",failed:"操作失败，请核验目标与备份"};
export function WorkspacePanel({sessionId,busy,onClose,onChanged}:{sessionId:string|null;busy:boolean;onClose():void;onChanged():Promise<void>}){const workspace=useWorkspace(sessionId,!busy),[preview,setPreview]=useState<WorkspacePreview|null>(null),[exportPreview,setExportPreview]=useState<ExportPreview|null>(null),[selected,setSelected]=useState<string[]>([]),[results,setResults]=useState<ExportResult[]>([]),[backups,setBackups]=useState<BackupView[]|null>(null),[working,setWorking]=useState(false),[error,setError]=useState("");
  useEffect(()=>{setSelected([]);setPreview(null);setExportPreview(null);setResults([]);},[sessionId]);
  const run=async(fn:()=>Promise<void>)=>{if(working)return;setWorking(true);setError("");try{await fn();}catch(e){setError(String(e));}finally{setWorking(false);}};
  const refreshBackups=async()=>setBackups(await window.desktop.exports.listBackups());
  return <div className="modal-backdrop"><section className="settings-modal workspace-panel" role="dialog" aria-modal="true" aria-label="工作区"><header><div><h2>工作区</h2><p>源目录保持独立 · Agent 只操作隔离副本</p></div><button aria-label="关闭工作区" onClick={onClose} disabled={working}>×</button></header><div className="workspace-content"><div className="workspace-toolbar"><span>{workspace.view?.sourceLabel??"尚未绑定源目录"}</span><button disabled={!sessionId||busy||working||!!workspace.view?.sourceLabel} onClick={()=>void run(async()=>{setPreview(await window.desktop.workspaces.previewSelection(sessionId!));})}>选择文件夹</button><button disabled={working||busy} onClick={()=>void run(refreshBackups)}>备份管理</button><button disabled={working||busy} onClick={()=>void run(workspace.refresh)}>刷新</button></div>{busy&&<p role="status">运行中：导入、写回、导出和恢复暂不可用。</p>}{(error||workspace.error)&&<p role="alert">{error||workspace.error}</p>}
    {backups!==null?<div data-testid="workspace-backups"><h3>独立恢复备份</h3><p>备份不随会话删除。最多 1 GiB／工作区；不会自动清理旧备份。</p>{!backups.length&&<p>暂无备份</p>}{backups.map(b=><div className="backup-row" key={b.id}><span>{b.name}<small>{b.size} 字节 · {new Date(b.createdAt).toLocaleString()} · {b.id}</small></span><button aria-label="恢复备份" disabled={working||busy} onClick={()=>void run(async()=>{setResults([await window.desktop.exports.restoreBackup(b.id)]);await refreshBackups();})}>恢复</button><button aria-label="删除备份" disabled={working||busy} onClick={()=>void run(async()=>{await window.desktop.exports.removeBackups([b.id]);await refreshBackups();})}>删除</button></div>)}<button onClick={()=>setBackups(null)}>返回文件</button></div>:<><div className="workspace-columns"><section><h3>文件副本</h3><div data-testid="workspace-files" className="workspace-files">{workspace.files.map(f=><div key={f.relativePath}>{f.kind==="directory"?"▸":"▫"} {f.relativePath}<small>{f.kind==="file"?`${f.size} 字节`:"目录"}</small></div>)}{!workspace.files.length&&<p className="muted">暂无文件</p>}</div>{workspace.cursor&&<button onClick={()=>void run(workspace.more)}>加载更多文件</button>}</section><section><h3>与导入基线的差异</h3><WorkspaceDiff changes={workspace.changes} selected={selected} onSelect={setSelected} disabled={working||busy}/></section></div><div className="workspace-toolbar"><button className="primary" disabled={working||busy||!selected.length||!workspace.view?.sourceLabel} onClick={()=>void run(async()=>{setExportPreview(await window.desktop.exports.preview(sessionId!,selected));})}>预览写回</button><button disabled={working||busy||!selected.some(p=>workspace.files.some(f=>f.relativePath===p&&f.kind==="file"))} onClick={()=>void run(async()=>{setResults(await window.desktop.exports.exportToChosenDirectory(sessionId!,selected.filter(p=>workspace.files.some(f=>f.relativePath===p&&f.kind==="file"))));})}>所选改动另存到文件夹</button></div></>}
    {!!results.length&&<div data-testid="export-results" className="export-results">{results.map((r,i)=><p key={i}>{r.path} · {status[r.status]}{r.errorCode&&`（${r.errorCode}）`}{r.errorCode==="WRITE_APPLIED_NOT_DURABLE"&&"：目标已改变，但持久化未确认"}{r.backupId&&<small>恢复备份：{r.backupId}</small>}</p>)}</div>}</div></section>
    {preview&&<div className="modal-backdrop nested-modal"><section className="settings-modal export-dialog" role="dialog" aria-label="导入工作目录" aria-modal="true"><header><h2>导入工作目录</h2><button onClick={()=>setPreview(null)} disabled={working}>取消</button></header><div className="workspace-content"><p>{preview.entryCount} 项 · {preview.totalBytes} 字节。只创建本地隔离副本，原目录不会被修改；文件名和内容可能在后续发送给模型。</p><div className="workspace-files">{preview.entries.map(e=><p key={e.relativePath}>{e.relativePath}</p>)}</div>{preview.excluded.length>0&&<p>已排除：{preview.excluded.join("、")}</p>}{preview.truncated&&<p>此处仅展示前 100 项</p>}<button className="primary" disabled={working||busy} onClick={()=>void run(async()=>{await window.desktop.workspaces.importSelection(sessionId!,preview.grantId);setPreview(null);await workspace.refresh();await onChanged();})}>创建隔离副本</button></div></section></div>}
    {exportPreview&&<ExportDialog preview={exportPreview} disabled={busy} onClose={()=>setExportPreview(null)} onApply={async selections=>{setResults(await window.desktop.exports.apply(exportPreview.token,selections));setExportPreview(null);await workspace.refresh();}}/>}
  </div>;
}
