import { test, expect } from "@playwright/test";
import { mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { configure, launch, latestStatus } from "./helpers";
import { startModelServer, chatChunk, writeStream } from "../fixtures/openai-server";
test("real approval cards drive isolated write/read/command, reject without effects and stop a live container",async({},info)=>{
  const directory=mkdtempSync(join(tmpdir(),"fastgpt-sandbox-e2e-"));let stage=0;
  const server=await startModelServer((body,res)=>{const last=body.messages?.at(-1),user=body.messages?.filter(m=>m.role==="user").at(-1)?.content??"";let call:{name:string;arguments:string;id:string}|undefined;
    if(last?.role==="user"){stage=0;if(user.includes("拒绝"))call={id:"reject-write",name:"workspace_write",arguments:JSON.stringify({path:"denied.txt",text:"denied"})};else if(user.includes("停止"))call={id:"stop-command",name:"workspace_exec",arguments:JSON.stringify({command:"echo started; sleep 120 & wait",cwd:"."})};else call={id:"approved-write",name:"workspace_write",arguments:JSON.stringify({path:"note.txt",text:"批准的内容"})};}
    else if(!user.includes("拒绝")&&!user.includes("停止")){stage++;if(stage===1)call={id:"approved-read",name:"workspace_read",arguments:JSON.stringify({path:"note.txt",offset:0,maxBytes:65536})};if(stage===2)call={id:"approved-command",name:"workspace_exec",arguments:JSON.stringify({command:"echo live-output; sleep 2; printf '产物' > generated.txt",cwd:"."})};}
    writeStream(res,call?[chatChunk({tool_calls:[{index:0,id:call.id,type:"function",function:{name:call.name,arguments:call.arguments}}]}),chatChunk({},"tool_calls")]:[chatChunk({content:user.includes("拒绝")?"已尊重拒绝，没有写入文件。":"文件和命令执行完成。"}),chatChunk({},"stop")]);
  });const app=await launch(directory);
  try {const {page,session}=await configure(app,server.baseUrl);await page.reload();await expect(page.getByTestId("sandbox-state")).toBeVisible();await page.getByTestId("sandbox-state").click();await expect(page.getByRole("button",{name:"准备沙箱",exact:true})).toBeVisible({timeout:1000});await page.getByRole("button",{name:"准备沙箱",exact:true}).click();await expect(page.getByTestId("sandbox-state")).toContainText("已就绪",{timeout:20000});expect((await page.locator(".chat-header h2").boundingBox())!.width).toBeGreaterThan(80);
    await page.getByRole("textbox",{name:"消息",exact:true}).fill("执行完整文件流程");await page.getByRole("button",{name:"发送",exact:true}).click();let pending=page.locator(".trace-approval[data-state=pending]");await expect(pending).toContainText("note.txt");await pending.getByRole("button",{name:"批准本次"}).click();await expect(pending).toContainText(server.baseUrl);await pending.getByRole("button",{name:"批准本次"}).click();await expect(pending).toContainText("sleep 2");await page.waitForTimeout(2100);await pending.getByRole("button",{name:"批准本次"}).click();await expect(page.getByTestId("command-output")).toContainText("live-output");await expect(page.getByTestId("command-elapsed")).toBeVisible();await expect.poll(()=>latestStatus(page,session.id)).toBe("completed");
    const events=await page.evaluate(async id=>{const run=(await window.desktop.runs.list(id)).at(-1)!;return window.desktop.runs.events(run.id);},session.id);const finished=events.find(e=>e.type==="command_finished");expect(finished?.type==="command_finished"?finished.elapsedMs:0).toBeGreaterThan(1800);expect(finished?.type==="command_finished"?finished.elapsedMs:99999).toBeLessThan(4000);expect(events.some(e=>e.type==="command_started"&&e.id==="approved-command")).toBe(true);expect(events.filter(e=>e.type==="workspace_checkpoint")).toHaveLength(2);expect(JSON.stringify(server.requests)).toContain("批准的内容");expect((await page.evaluate(id=>window.desktop.workspaces.list(id),session.id)).entries.map(e=>e.relativePath)).toContain("generated.txt");await page.screenshot({path:info.outputPath("sandbox-agent.png")});
    await page.getByRole("textbox",{name:"消息",exact:true}).fill("拒绝写入");await page.getByRole("button",{name:"发送",exact:true}).click();await expect(pending).toContainText("denied.txt");await pending.getByRole("button",{name:"拒绝"}).click();await expect.poll(()=>latestStatus(page,session.id)).toBe("completed");expect((await page.evaluate(id=>window.desktop.workspaces.list(id),session.id)).entries.map(e=>e.relativePath)).not.toContain("denied.txt");
    await page.getByRole("textbox",{name:"消息",exact:true}).fill("停止正在执行的命令");await page.getByRole("button",{name:"发送",exact:true}).click();await expect(pending).toContainText("sleep 120");await pending.getByRole("button",{name:"批准本次"}).click();await expect(page.getByTestId("command-output").last()).toContainText("started");await page.getByRole("button",{name:"停止",exact:true}).click();await expect.poll(()=>latestStatus(page,session.id)).toBe("cancelled");
  }finally{await app.close();await server.close();rmSync(directory,{recursive:true,force:true});}
});
