import { syntheticAudioDevice,audioTracksEnded } from "./audio-fixture";
import { test,expect } from "@playwright/test";
import { mkdtempSync,rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { launch,configure } from "./helpers";
import { startFixtureModelServer } from "../fixtures/openai-server";
import { startTranscriptionServer } from "../fixtures/transcription-server";
test("cancelling pending native microphone consent releases the main operation and late consent cannot authorize a new capture",async()=>{
  test.skip(process.platform!=="darwin","macOS native consent boundary");
  const directory=mkdtempSync(join(tmpdir(),"fastgpt-voice-consent-")),asr=await startTranscriptionServer(),model=await startFixtureModelServer(),app=await launch(directory);
  try{const {page}=await configure(app,model.baseUrl);await page.evaluate(baseUrl=>window.desktop.speech.save({enabled:true,name:"ASR",baseUrl,modelId:"asr",timeoutMs:10000,allowInsecureHttp:true},"key"),asr.baseUrl);
    await app.evaluate(({systemPreferences})=>{const g=globalThis as any;g.__consentCalls=0;systemPreferences.askForMediaAccess=async()=>{g.__consentCalls++;return g.__consentCalls===1?new Promise<boolean>(resolve=>{g.__releaseConsent=resolve;}):true;};});
    await syntheticAudioDevice(page);await page.reload();await page.getByRole("button",{name:"开始录音",exact:true}).click();await expect.poll(()=>app.evaluate(()=> (globalThis as any).__consentCalls)).toBe(1);await expect(page.getByTestId("voice-state")).toContainText("等待麦克风权限");
    await page.getByRole("button",{name:"取消录音",exact:true}).click();await page.getByRole("button",{name:"开始录音",exact:true}).click();await expect(page.getByTestId("voice-state")).toContainText("录音中");await app.evaluate(()=>{(globalThis as any).__releaseConsent(true);});await expect(page.getByTestId("voice-state")).toContainText("录音中");
    await page.getByRole("button",{name:"取消录音",exact:true}).click();expect(await audioTracksEnded(page)).toBe(true);expect(asr.requests).toHaveLength(0);expect(model.requests).toHaveLength(0);
  }finally{await app.evaluate(()=>{(globalThis as any).__releaseConsent?.(false);}).catch(()=>{});await app.close();await asr.close();await model.close();rmSync(directory,{recursive:true,force:true});}
});
test("synthetic audio with real MediaRecorder uploads multipart only on stop, inserts without replacing draft or auto-sending, and cancels audio",async({},info)=>{const directory=mkdtempSync(join(tmpdir(),"fastgpt-voice-ui-")),asr=await startTranscriptionServer(),model=await startFixtureModelServer(),app=await launch(directory,{FASTGPT_DESKTOP_TEST_FAKE_AUDIO:"1"});try{const {page,session}=await configure(app,model.baseUrl);await page.evaluate(baseUrl=>window.desktop.speech.save({enabled:true,name:"ASR test",baseUrl,modelId:"asr-test",timeoutMs:10000,allowInsecureHttp:true},"speech-secret"),asr.baseUrl);await syntheticAudioDevice(page);await page.reload();await expect(page.getByRole("button",{name:"开始录音",exact:true})).toBeEnabled();await page.getByRole("textbox",{name:"消息",exact:true}).fill("用户原草稿");await page.getByRole("button",{name:"开始录音",exact:true}).click();await expect(page.getByTestId("voice-state")).toContainText("录音中");await expect.poll(()=>page.getByTestId("voice-state").textContent()).toContain("1 秒");expect(asr.requests).toHaveLength(0);await page.getByRole("button",{name:"停止并转写",exact:true}).click();await expect(page.getByTestId("voice-transcript")).toHaveValue("转写中文");await expect(page.getByRole("textbox",{name:"消息",exact:true})).toHaveValue("用户原草稿");expect(await audioTracksEnded(page)).toBe(true);expect(asr.requests).toHaveLength(1);expect(asr.requests[0].bytes.toString()).toContain('filename="recording.webm"');expect(model.requests).toHaveLength(0);await page.getByRole("textbox",{name:"消息",exact:true}).fill("用户新输入");await page.getByRole("button",{name:"插入草稿",exact:true}).click();await expect(page.getByRole("textbox",{name:"消息",exact:true})).toHaveValue("用户新输入\n转写中文");expect(await page.evaluate(id=>window.desktop.sessions.messages(id),session.id)).toEqual([]);await page.getByRole("button",{name:"开始录音",exact:true}).click();await expect(page.getByTestId("voice-state")).toContainText("录音中");await page.getByRole("button",{name:"取消录音",exact:true}).click();await expect(page.getByTestId("voice-state")).not.toContainText("录音中");expect(await audioTracksEnded(page)).toBe(true);expect(asr.requests).toHaveLength(1);await page.screenshot({path:info.outputPath("voice-input.png")});}finally{await app.close();await asr.close();await model.close();rmSync(directory,{recursive:true,force:true});}});
test("switching session while ASR is pending discards its late text and releases capture operation",async()=>{const directory=mkdtempSync(join(tmpdir(),"fastgpt-voice-switch-"));let release:(()=>void)|undefined;const asr=await startTranscriptionServer(res=>{release=()=>{res.setHeader("Content-Type","application/json");res.end(JSON.stringify({text:"迟到的录音文字"}));};}),model=await startFixtureModelServer(),app=await launch(directory,{FASTGPT_DESKTOP_TEST_FAKE_AUDIO:"1"});try{const {page,provider}=await configure(app,model.baseUrl);const second=await page.evaluate(id=>window.desktop.sessions.create({title:"另一个会话",providerId:id}),provider.id);await page.evaluate(baseUrl=>window.desktop.speech.save({enabled:true,name:"ASR",baseUrl,modelId:"asr",timeoutMs:10000,allowInsecureHttp:true},"key"),asr.baseUrl);await syntheticAudioDevice(page);await page.reload();await page.getByRole("button",{name:"开始录音",exact:true}).click();await expect(page.getByTestId("voice-state")).toContainText("录音中");await page.waitForTimeout(350);await page.getByRole("button",{name:"停止并转写",exact:true}).click();await expect.poll(()=>asr.requests.length).toBe(1);expect(await audioTracksEnded(page)).toBe(true);await page.locator(`button.session-title`).filter({hasText:"恢复会话"}).click();await page.getByRole("textbox",{name:"消息",exact:true}).fill("用户新输入");release?.();await expect(page.getByTestId("voice-transcript")).toHaveCount(0);await expect(page.getByRole("textbox",{name:"消息",exact:true})).toHaveValue("用户新输入");expect(model.requests).toHaveLength(0);expect((await page.evaluate(()=>window.desktop.sessions.list())).some(s=>s.id===second.id)).toBe(true);}finally{await app.close();await asr.close();await model.close();rmSync(directory,{recursive:true,force:true});}});
