import { test,expect } from "@playwright/test";
import { mkdtempSync,mkdirSync,writeFileSync,readFileSync,readdirSync,rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";
import { launch,configure } from "./helpers";
import { startModelServer,writeStream,chatChunk } from "../fixtures/openai-server";
test("crash recovery keeps checkpoint and backup, revokes approval, never replays, and session deletion preserves recoverable source bytes",async()=>{
 const directory=mkdtempSync(join(tmpdir(),"fastgpt-recover-")),source=mkdtempSync(join(tmpdir(),"fastgpt-recover-source-"));writeFileSync(join(source,"note.txt"),"original");
 const server=await startModelServer((body,res)=>writeStream(res,body.messages?.at(-1)?.role==="user"?[chatChunk({tool_calls:[{index:0,id:"write-"+server.requests.length,type:"function",function:{name:"workspace_write",arguments:JSON.stringify({path:"note.txt",text:body.messages?.at(-1)?.content==="pending"?"MUST_NOT_WRITE":"changed"})}}]}),chatChunk({},"tool_calls")]:[chatChunk({content:"done"}),chatChunk({},"stop")]));
 let app:Awaited<ReturnType<typeof launch>>|null=await launch(directory);
 try{
  const {page,session}=await configure(app,server.baseUrl);await app.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]});dialog.showMessageBox=async()=>({response:0,checkboxChecked:false});},source);
  const p=await page.evaluate(id=>window.desktop.workspaces.previewSelection(id),session.id);await page.evaluate(({sid,g})=>window.desktop.workspaces.importSelection(sid,g),{sid:session.id,g:p.grantId});await page.reload();
  await page.getByRole("textbox",{name:"消息",exact:true}).fill("write");await page.getByRole("button",{name:"发送",exact:true}).click();await page.locator(".trace-approval[data-state=pending]").getByRole("button",{name:"批准本次"}).click();await expect.poll(()=>page.evaluate(async id=>(await window.desktop.runs.list(id)).at(-1)?.status,session.id)).toBe("completed");
  const before=await page.evaluate(id=>window.desktop.workspaces.list(id),session.id),preview=await page.evaluate(id=>window.desktop.exports.preview(id,["note.txt"]),session.id),written=await page.evaluate(token=>window.desktop.exports.apply(token,[{path:"note.txt",action:"write"}]),preview.token);expect(written[0].status).toBe("written");expect(readFileSync(join(source,"note.txt"),"utf8")).toBe("changed");
  await page.getByRole("textbox",{name:"消息",exact:true}).fill("pending");await page.getByRole("button",{name:"发送",exact:true}).click();await expect(page.locator(".trace-approval[data-state=pending]")).toHaveCount(1);const pending=(await page.evaluate(id=>window.desktop.runs.list(id),session.id)).at(-1)!,requests=server.requests.length;
  const orphan=randomUUID(),foreign=randomUUID(),artifacts=join(directory,"artifacts");mkdirSync(join(artifacts,orphan));const {statSync}=await import("node:fs");const identity=statSync(join(artifacts,orphan),{bigint:true});writeFileSync(join(artifacts,".owners",orphan+".json"),JSON.stringify({key:orphan,device:String(identity.dev),inode:String(identity.ino),state:"temporary"}));mkdirSync(join(artifacts,foreign));writeFileSync(join(artifacts,foreign,"sentinel"),"FOREIGN");writeFileSync(join(artifacts,".owners",foreign+".json"),JSON.stringify({key:foreign,device:"0",inode:"0",state:"temporary"}));
  const exited=new Promise<void>(r=>app!.process().once("exit",()=>r()));app.process().kill("SIGKILL");await exited;app=null;app=await launch(directory);const restored=await app.firstWindow();await restored.waitForFunction(()=>!!window.desktop);
  expect(await restored.evaluate(async id=>(await window.desktop.runs.list(id)).at(-1)?.status,session.id)).toBe("interrupted");const events=await restored.evaluate(id=>window.desktop.runs.events(id),pending.id);expect(events.some(e=>e.type==="approval_decided"&&e.decision==="revoked")).toBe(true);expect(await restored.evaluate(id=>window.desktop.workspaces.list(id),session.id)).toEqual(before);expect(readdirSync(artifacts)).not.toContain(orphan);expect(readFileSync(join(artifacts,foreign,"sentinel"),"utf8")).toBe("FOREIGN");await restored.waitForTimeout(300);expect(server.requests).toHaveLength(requests);
  await restored.evaluate(id=>window.desktop.sessions.remove(id),session.id);expect((await restored.evaluate(()=>window.desktop.exports.listBackups())).some(b=>b.id===written[0].backupId)).toBe(true);await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:0,checkboxChecked:false});});expect((await restored.evaluate(id=>window.desktop.exports.restoreBackup(id),written[0].backupId!)).status).toBe("written");expect(readFileSync(join(source,"note.txt"),"utf8")).toBe("original");expect(readdirSync(artifacts)).toEqual(expect.arrayContaining([".owners",foreign]));expect(readdirSync(artifacts)).toHaveLength(2);
 }finally{await app?.close();await server.close();rmSync(directory,{recursive:true,force:true});rmSync(source,{recursive:true,force:true});}
});
