import { afterEach, expect, test } from "vitest";
import { fileFixture } from "./file-feature-fixture";
import { namespaceA as n, namespaceB } from "../../../tests/fixtures/data";
import { ApprovalService } from "../src/main/tools/approval-service";
import type { AgentEvent, ApprovalRequestView, ToolCall } from "../../../packages/shared/src/index";
const cleanup:(()=>Promise<void>)[]=[];afterEach(async()=>{for(const fn of cleanup.splice(0))await fn();});
async function fixture(){const x=await fileFixture();cleanup.push(x.cleanup);const run=x.store.runs.createWithUserMessage(n,x.session.id,"test");x.store.runs.transition(n,run.id,"running");const context={namespace:n,sessionId:x.session.id,runId:run.id},events:AgentEvent[]=[];let principal=n;const service=new ApprovalService({store:x.store,principal:()=>principal,persistEvent:async(c,e)=>{if(e.type==="status")x.store.runs.transition(c.namespace,c.runId,e.status);x.store.runs.appendEvent(c.namespace,c.runId,e);events.push(e);}});const call:ToolCall={id:"call",name:"workspace_exec",arguments:'{"command":"printf ok","cwd":"."}'},view:ApprovalRequestView={kind:"command",relativePath:null,command:"printf ok",arguments:call.arguments,destinationLabel:"隔离沙箱 /workspace"};return {...x,service,context,events,call,view,switch:()=>{principal=namespaceB;}};}
async function requested(x:Awaited<ReturnType<typeof fixture>>){const promise=x.service.request(x.context,x.call,x.view,new AbortController().signal);void promise.catch(()=>{});for(let i=0;i<50&&!x.events.some(e=>e.type==="approval_requested");i++)await new Promise(r=>setTimeout(r,2));const request=x.events.find(e=>e.type==="approval_requested");expect(request?.type).toBe("approval_requested");return {promise,id:request!.type==="approval_requested"?request!.approval.id:""};}
test("approval persists full parameters and waiting status; approved grant is bound and consumed exactly once",async()=>{const x=await fixture(),pending=await requested(x);expect(x.store.runs.get(n,x.context.runId).status).toBe("waiting_approval");const record=x.store.approvals.get(n,pending.id);expect(record.view.arguments).toContain("printf ok");await expect(x.service.decide(namespaceB,pending.id,"approved")).rejects.toMatchObject({code:"NOT_FOUND"});await x.service.decide(n,pending.id,"approved");expect(await pending.promise).toBe("approved");expect(x.store.runs.get(n,x.context.runId).status).toBe("running");expect(()=>x.service.consume(x.context,{...x.call,arguments:'{"command":"changed","cwd":"."}'})).toThrow();expect(()=>x.service.consume(x.context,x.call)).not.toThrow();expect(()=>x.service.consume(x.context,x.call)).toThrow();await expect(x.service.decide(n,pending.id,"approved")).rejects.toMatchObject({code:"PERMISSION_DENIED"});});
test("rejection resumes the run without a grant and cancellation revokes pending UI authority",async()=>{const x=await fixture(),pending=await requested(x);await x.service.decide(n,pending.id,"rejected");expect(await pending.promise).toBe("rejected");expect(x.store.runs.get(n,x.context.runId).status).toBe("running");expect(()=>x.service.consume(x.context,x.call)).toThrow();const abort=new AbortController(),call={...x.call,id:"next"},promise=x.service.request(x.context,call,x.view,abort.signal);void promise.catch(()=>{});for(let i=0;i<50&&x.events.filter(e=>e.type==="approval_requested").length<2;i++)await new Promise(r=>setTimeout(r,2));const e=x.events.filter(e=>e.type==="approval_requested").at(-1)!;expect(e.type).toBe("approval_requested");abort.abort();await expect(promise).rejects.toMatchObject({code:"CANCELLED"});const id=e.type==="approval_requested"?e.approval.id:"";await expect(x.service.decide(n,id,"approved")).rejects.toMatchObject({code:"PERMISSION_DENIED"});expect(x.store.approvals.get(n,id).view.state).toBe("revoked");});
test("identity change and terminal runs invalidate approval and never create reusable grants",async()=>{const x=await fixture(),pending=await requested(x);x.switch();await expect(x.service.decide(n,pending.id,"approved")).rejects.toMatchObject({code:"PERMISSION_DENIED"});x.service.revokeRun(n,x.context.runId);await expect(pending.promise).rejects.toMatchObject({code:"CANCELLED"});});
test("approved but cancelled unconsumed grants are released instead of exhausting later approvals",async()=>{const x=await fixture();for(let i=0;i<260;i++){const abort=new AbortController(),call={...x.call,id:`call-${i}`},promise=x.service.request(x.context,call,x.view,abort.signal);void promise.catch(()=>{});for(let tick=0;tick<10&&!x.events.some(e=>e.type==="approval_requested"&&e.approval.callId===call.id);tick++)await Promise.resolve();const e=x.events.find(e=>e.type==="approval_requested"&&e.approval.callId===call.id);expect(e?.type).toBe("approval_requested");if(e?.type==="approval_requested")await x.service.decide(n,e.approval.id,"approved");await promise;abort.abort();}});
