import { afterEach,expect,test,vi } from "vitest";
import { MediaPermissionService } from "../src/main/speech/media-permissions";
import { TranscriptionService } from "../src/main/speech/transcription-service";
import { SecretStore } from "../src/main/credentials";
import { openStore } from "../../../packages/storage/src/index";
import { namespaceA as n,namespaceB,validDraft } from "../../../tests/fixtures/data";
const cleanup:(()=>void)[]=[];afterEach(()=>{cleanup.splice(0).reverse().forEach(fn=>fn());vi.restoreAllMocks();});
async function fixture(){const store=openStore(":memory:");cleanup.push(()=>store.close());let principal=n;const wc={id:7,getURL:()=>"app://desktop/index.html",isDestroyed:()=>false},secrets=new SecretStore(store.credentials,{isAvailable:async()=>false,isSecure:async()=>false,encrypt:async()=>new Uint8Array(),decrypt:async()=>""}),speech=new TranscriptionService({store,secrets,principal:()=>principal,window:()=>7}),service=new MediaPermissionService({speech,principal:()=>principal,window:()=>wc,consent:async()=>true}),provider=store.providers.save(n,validDraft,null),session=store.sessions.create(n,{title:"voice",providerId:provider.id});cleanup.push(()=>{service.shutdown();speech.shutdown();});await speech.save(n,{enabled:true,name:"ASR",baseUrl:"https://asr.example/v1",modelId:"asr",timeoutMs:10000,allowInsecureHttp:false},"key");return {wc,service,speech,store,session,switch:()=>{principal=namespaceB;}};}
const details={isMainFrame:true,requestingUrl:"app://desktop/index.html",securityOrigin:"app://desktop",mediaTypes:["audio"]};
test("cancelCapture is limited to the current namespace/session/main window and releases pending consent",async()=>{const x=await fixture();let release!:(v:boolean)=>void;let calls=0;const consent=new Promise<boolean>(r=>release=r),media=new MediaPermissionService({speech:x.speech,principal:()=>n,window:()=>x.wc,consent:()=>++calls===1?consent:Promise.resolve(true)});cleanup.push(()=>media.shutdown());const pending=media.beginCapture(n,x.session.id,x.wc).catch(e=>e);await Promise.resolve();expect(()=>media.cancelCapture(namespaceB,x.session.id,x.wc)).toThrow();expect(()=>media.cancelCapture(n,x.session.id,{...x.wc,id:8})).toThrow();expect(()=>media.cancelCapture(n,"foreign-session",x.wc)).toThrow();media.cancelCapture(n,x.session.id,x.wc);expect(await pending).toMatchObject({code:"CANCELLED"});const next=await media.beginCapture(n,x.session.id,x.wc);release(true);await Promise.resolve();expect(x.speech.captureScope(n,next.operationId)).toEqual({sessionId:x.session.id,owner:7});media.cancelCapture(n,x.session.id,x.wc);let allowed=true;media.request(x.wc,"media",v=>{allowed=v;},details);expect(allowed).toBe(false);});
function request(x:Awaited<ReturnType<typeof fixture>>,d:unknown=details,wc=x.wc,permission="media"){let allowed:boolean|undefined;x.service.request(wc,permission,v=>{allowed=v;},d);return allowed;}
test("only a single main-owned capture grant authorizes an audio-only request and permission checks never preauthorize reuse",async()=>{const x=await fixture();expect(request(x)).toBe(false);const op=await x.service.beginCapture(n,x.session.id,x.wc);expect(x.service.check(x.wc,"media","app://desktop",{isMainFrame:true,mediaType:"audio"})).toBe(false);expect(request(x)).toBe(true);expect(request(x)).toBe(false);x.service.revoke(op.operationId);});
test("null/foreign windows, subframes, camera/combined/unknown/incomplete requests remain denied",async()=>{const x=await fixture(),op=await x.service.beginCapture(n,x.session.id,x.wc);for(const d of [{...details,isMainFrame:false},{...details,mediaTypes:["video"]},{...details,mediaTypes:["audio","video"]},{...details,mediaTypes:[]},{...details,mediaTypes:undefined},{...details,securityOrigin:"https://evil.example"},{isMainFrame:true}])expect(request(x,d)).toBe(false);expect(request(x,details,{...x.wc,id:8})).toBe(false);expect(request(x,details,x.wc,"notifications")).toBe(false);let granted=true;x.service.request(null,"media",v=>{granted=v;},details);expect(granted).toBe(false);expect(x.service.check(null,"media","app://desktop",{isMainFrame:true,mediaType:"audio"})).toBe(false);expect(request(x)).toBe(true);x.service.revoke(op.operationId);});
test("capture grant expiry and identity/config revocation deny requests without extending the full operation lifetime",async()=>{const x=await fixture(),at=performance.now(),clock=vi.spyOn(performance,"now").mockReturnValue(at),op=await x.service.beginCapture(n,x.session.id,x.wc);clock.mockReturnValue(at+60001);expect(request(x)).toBe(false);x.service.revoke(op.operationId);clock.mockReturnValue(at+60002);const next=await x.service.beginCapture(n,x.session.id,x.wc);x.switch();expect(request(x)).toBe(false);x.service.revoke(next.operationId);});
