import { afterEach,expect,test } from "vitest";
import { SecretStore } from "../src/main/credentials";
import { TranscriptionService } from "../src/main/speech/transcription-service";
import { openStore } from "../../../packages/storage/src/index";
import { namespaceA as n,namespaceB,validDraft } from "../../../tests/fixtures/data";
import { startTranscriptionServer,webmBytes } from "../../../tests/fixtures/transcription-server";
const closers:(()=>Promise<void>|void)[]=[];afterEach(async()=>{for(const close of closers.splice(0).reverse())await close();});
const draft={enabled:true,name:"ASR",baseUrl:"https://asr.example/v1",modelId:"asr-only",timeoutMs:10000,allowInsecureHttp:false};
function fixture(){const store=openStore(":memory:");closers.push(()=>store.close());let principal=n,gate:Promise<void>|null=null;const secrets=new SecretStore(store.credentials,{isAvailable:async()=>true,isSecure:async()=>true,encrypt:async s=>Buffer.from([...s].reverse().join("")),decrypt:async bytes=>{if(gate)await gate;return [...Buffer.from(bytes).toString()].reverse().join("");}}),service=new TranscriptionService({store,secrets,principal:()=>principal,window:()=>7}),provider=store.providers.save(n,validDraft,null),session=store.sessions.create(n,{title:"audio",providerId:provider.id});closers.push(()=>service.shutdown());return {store,secrets,service,session,switch:()=>{principal=namespaceB;},gate:(p:Promise<void>)=>{gate=p;}};}
test("speech credentials are independent, masked and namespace-scoped; same window allows one operation",async()=>{const x=fixture();await x.secrets.put("chat-secret",n);const view=await x.service.save(n,draft,"speech-secret");expect(view).toMatchObject({modelId:"asr-only",credentialState:"persistent"});expect(JSON.stringify(view)).not.toContain("speech-secret");await expect(x.service.get(namespaceB)).rejects.toMatchObject({code:"PERMISSION_DENIED"});expect(x.store.transcriptions.get(namespaceB)).toBeNull();const op=await x.service.begin(n,x.session.id,7);await expect(x.service.begin(n,x.session.id,7)).rejects.toMatchObject({code:"AUDIO_BUSY"});await expect(x.service.begin(n,x.session.id,8)).rejects.toMatchObject({code:"PERMISSION_DENIED"});x.service.cancel(n,op.operationId);expect((await x.service.begin(n,x.session.id,7)).operationId).not.toBe(op.operationId);});
test("actual transcription returns text without storing audio/history and an operation cannot replay",async()=>{const x=fixture(),server=await startTranscriptionServer();closers.push(server.close);await x.service.save(n,{...draft,baseUrl:server.baseUrl,allowInsecureHttp:true},"speech-secret");const op=await x.service.begin(n,x.session.id,7),audio={sessionId:x.session.id,operationId:op.operationId,mimeType:"audio/webm",bytes:webmBytes};expect(await x.service.submit(n,audio)).toEqual({...op,text:"转写中文"});expect(x.store.sessions.messages(n,x.session.id)).toEqual([]);expect(server.requests[0].headers.authorization).toBe("Bearer speech-secret");await expect(x.service.submit(n,audio)).rejects.toMatchObject({code:"PERMISSION_DENIED"});});
test.each(["config","identity","session","cancel"])("%s changes while a secret is decrypting cannot launch an old transcription",async change=>{const x=fixture(),server=await startTranscriptionServer();closers.push(server.close);await x.service.save(n,{...draft,baseUrl:server.baseUrl,allowInsecureHttp:true},"speech-secret");const op=await x.service.begin(n,x.session.id,7);let release!:()=>void;const gate=new Promise<void>(r=>{release=r;});x.gate(gate);const pending=x.service.submit(n,{sessionId:x.session.id,operationId:op.operationId,mimeType:"audio/webm",bytes:webmBytes});pending.catch(()=>{});if(change==="config")await x.service.save(n,{...draft,baseUrl:server.baseUrl,allowInsecureHttp:true,modelId:"new-asr"});if(change==="identity")x.switch();if(change==="session")x.store.sessions.remove(n,x.session.id);if(change==="cancel")x.service.cancel(n,op.operationId);release();await expect(pending).rejects.toThrow();expect(server.requests).toEqual([]);});
