import { afterEach,expect,test,vi } from "vitest";
import { VoiceRecorder,recordingMime } from "../src/renderer/hooks/voice-recorder";
class DeviceRecorder extends EventTarget{state:RecordingState="inactive";mimeType="audio/webm;codecs=opus";ondataavailable:((event:BlobEvent)=>void)|null=null;onstop:(()=>void)|null=null;onerror:((event:Event)=>void)|null=null;start(){this.state="recording";}stop(){this.state="inactive";this.ondataavailable?.({data:new Blob([new Uint8Array([0x1a,0x45,0xdf,0xa3,1,2,3,4])])}as BlobEvent);this.onstop?.();}chunk(bytes:number){this.ondataavailable?.({data:new Blob([new Uint8Array(bytes)])}as BlobEvent);}}
function device(){const tracks=[1,2].map(()=>{const track=new EventTarget()as EventTarget&{kind:string;readyState:string;stop():void};track.kind="audio";track.readyState="live";track.stop=()=>{track.readyState="ended";};return track;}),stream={getTracks:()=>tracks}as unknown as MediaStream,recorder=new DeviceRecorder(),errors:Error[]=[];const voice=new VoiceRecorder({getUserMedia:async()=>stream,createRecorder:()=>recorder as unknown as MediaRecorder,onFailure:e=>errors.push(e)});return {voice,tracks,recorder,errors,stream};}
afterEach(()=>vi.useRealTimers());
test.each(["cancel","timeout"])("%s releases a pending acquisition without waiting for the device and stops any late stream",async kind=>{vi.useFakeTimers();const x=device();let acquire!:(stream:MediaStream)=>void;const voice=new VoiceRecorder({getUserMedia:()=>new Promise(resolve=>{acquire=resolve;}),createRecorder:()=>x.recorder as unknown as MediaRecorder});let failure:unknown;const pending=voice.start("audio/webm").catch(e=>{failure=e;});if(kind==="cancel")voice.cancel();else await vi.advanceTimersByTimeAsync(60000);await vi.advanceTimersByTimeAsync(0);expect(failure).toBeInstanceOf(Error);acquire(x.stream);await pending;await Promise.resolve();expect(x.tracks.every(t=>t.readyState==="ended")).toBe(true);expect(x.recorder.state).toBe("inactive");});
test("actual supported encoding is selected and stopped capture releases every track and returns audio bytes",async()=>{expect(recordingMime(m=>m==="audio/mp4")).toBe("audio/mp4");const x=device();await x.voice.start("audio/webm;codecs=opus");const data=await x.voice.stop();expect(data.mimeType).toBe("audio/webm;codecs=opus");expect(data.bytes).toEqual(new Uint8Array([0x1a,0x45,0xdf,0xa3,1,2,3,4]));expect(x.tracks.every(t=>t.readyState==="ended")).toBe(true);});
test("cancelled device acquisition releases late tracks and never starts a recorder",async()=>{const x=device();let acquire!:(stream:MediaStream)=>void;const voice=new VoiceRecorder({getUserMedia:()=>new Promise(r=>{acquire=r;}),createRecorder:()=>x.recorder as unknown as MediaRecorder});const pending=voice.start("audio/webm");pending.catch(()=>{});await expect.poll(()=>typeof acquire==="function",{timeout:100}).toBe(true);voice.cancel();acquire(x.stream);await expect(pending).rejects.toThrow();expect(x.recorder.state).toBe("inactive");expect(x.tracks.every(t=>t.readyState==="ended")).toBe(true);});
test.each(["bytes","duration","device"])("%s limit/failure stops all tracks and cannot return an uploadable recording",async kind=>{vi.useFakeTimers();const x=device();await x.voice.start("audio/webm");if(kind==="bytes")x.recorder.chunk(20*1024*1024+1);if(kind==="duration")await vi.advanceTimersByTimeAsync(120000);if(kind==="device")x.tracks[0].dispatchEvent(new Event("ended"));expect(x.tracks.every(t=>t.readyState==="ended")).toBe(true);expect(x.errors).toHaveLength(1);await expect(x.voice.stop()).rejects.toThrow();});
test("empty final recording is rejected but cleanup permits a new capture",async()=>{const x=device();await x.voice.start("audio/webm");x.recorder.stop=()=>{x.recorder.state="inactive";x.recorder.onstop?.();};await expect(x.voice.stop()).rejects.toThrow(/为空/);expect(x.tracks.every(t=>t.readyState==="ended")).toBe(true);await expect(x.voice.start("audio/webm")).resolves.toBeUndefined();x.voice.cancel();});
