import { afterEach, expect, test } from "vitest";
import { join } from "node:path";
import { readFile, writeFile } from "node:fs/promises";
import { fileFixture } from "./file-feature-fixture";
import { namespaceA as n, validDraft } from "../../../tests/fixtures/data";
import { WorkspaceService } from "../src/main/workspaces/workspace-service";
import { ApprovalService } from "../src/main/tools/approval-service";
import { registerWorkspaceTools } from "../src/main/tools/workspace-tools";
import { ToolGateway, createBuiltinTools } from "../src/main/tool-gateway";
import type { AgentEvent, ToolCall } from "../../../packages/shared/src/index";
import { DockerSandboxProvider } from "../../../packages/sandbox/src/index";
import { ImageService } from "../../../packages/sandbox/src/index";
const cleanup:(()=>Promise<void>)[]=[];afterEach(async()=>{for(const fn of cleanup.splice(0))await fn();});
async function fixture({importSource=true}:{importSource?:boolean}={}){const x=await fileFixture();cleanup.push(x.cleanup);await writeFile(join(x.source,"input.txt"),"源文件");const workspace=new WorkspaceService({store:x.store,artifacts:x.artifacts,files:x.files,grants:x.grants,principal:()=>n,window:()=>7,pick:async()=>x.source,credentialRoots:[]});if(importSource){const preview=await workspace.previewSelection(n,x.session.id);await workspace.importSelection(n,x.session.id,preview.grantId,new AbortController().signal);}
  const snapshot={name:validDraft.name,baseUrl:validDraft.baseUrl,modelId:validDraft.modelId,contextWindow:validDraft.contextWindow,maxOutputTokens:validDraft.maxOutputTokens,timeoutMs:validDraft.timeoutMs,capabilities:validDraft.capabilities,providerId:x.provider.id,revision:x.provider.revision},run=x.store.runs.createWithUserMessage(n,x.session.id,"tool",{snapshot});x.store.runs.transition(n,run.id,"running");const context={namespace:n,sessionId:x.session.id,runId:run.id},events:AgentEvent[]=[];const persistEvent=async(c:typeof context,e:AgentEvent)=>{if(e.type==="status")x.store.runs.transition(c.namespace,c.runId,e.status);x.store.runs.appendEvent(c.namespace,c.runId,e);events.push(e);},approvals=new ApprovalService({store:x.store,principal:()=>n,persistEvent}),registry=createBuiltinTools();
  const client={assertLocal:async()=>{throw new Error("not prepared");},run:async()=>{throw new Error("not prepared");},start:async()=>{throw new Error("not prepared");}},images=new ImageService({client,assetDirectory:"packages/sandbox/image",stateDirectory:join(x.root,"image")}),sandbox=new DockerSandboxProvider({client,images,files:x.artifacts,stateDirectory:join(x.root,"sandbox-owners")});registerWorkspaceTools(registry,{workspace,approvals,sandbox,store:x.store,persistEvent});const gateway=new ToolGateway(x.store.runs,registry,approvals);return {...x,workspace,context,events,approvals,gateway};}
async function decision(x:Awaited<ReturnType<typeof fixture>>,call:ToolCall,approved:boolean){const started=x.gateway.execute(call,x.context,new AbortController().signal);void started.catch(()=>{});for(let i=0;i<50&&!x.events.some(e=>e.type==="approval_requested"&&e.approval.callId===call.id);i++)await new Promise(r=>setTimeout(r,2));const e=x.events.find(e=>e.type==="approval_requested"&&e.approval.callId===call.id);expect(e?.type).toBe("approval_requested");if(e?.type==="approval_requested")await x.approvals.decide(n,e.approval.id,approved?"approved":"rejected");return started;}
test.skipIf(process.platform==="win32")("writes only approved private snapshots, reads only approved bytes to the pinned model, and never changes the source",async()=>{const x=await fixture(),write={id:"write",name:"workspace_write",arguments:JSON.stringify({path:"input.txt",text:"新的中文内容"})};const started=x.gateway.execute(write,x.context,new AbortController().signal);void started.catch(()=>{});for(let i=0;i<50&&!x.events.some(e=>e.type==="approval_requested");i++)await new Promise(r=>setTimeout(r,2));expect((await x.workspace.read(n,x.session.id,"input.txt",0,65536)).text).toBe("源文件");const e=x.events.find(e=>e.type==="approval_requested");expect(e?.type).toBe("approval_requested");if(e?.type==="approval_requested")await x.approvals.decide(n,e.approval.id,"approved");expect((await started).isError).toBe(false);expect(await readFile(join(x.source,"input.txt"),"utf8")).toBe("源文件");expect(x.events.some(e=>e.type==="workspace_checkpoint")).toBe(true);
  const read={id:"read",name:"workspace_read",arguments:JSON.stringify({path:"input.txt",offset:0,maxBytes:65536})};const result=await decision(x,read,true);expect(result.content).toContain("新的中文内容");const card=x.events.find(e=>e.type==="approval_requested"&&e.approval.callId==="read");expect(card?.type==="approval_requested"?card.approval.destinationLabel:"").toContain(validDraft.baseUrl);});
test.skipIf(process.platform==="win32")("rejection is a completed error result, does not mutate files, and duplicate/unknown calls never replay",async()=>{const x=await fixture(),call={id:"denied",name:"workspace_write",arguments:JSON.stringify({path:"no.txt",text:"blocked"})};expect((await decision(x,call,false)).isError).toBe(true);expect((await x.workspace.list(n,x.session.id)).entries.some(e=>e.relativePath==="no.txt")).toBe(false);const count=x.events.length;expect((await x.gateway.execute(call,x.context,new AbortController().signal)).isError).toBe(true);expect(x.events).toHaveLength(count);x.store.runs.reserveToolCall(n,x.context.runId,{...call,id:"unknown"});await expect(x.gateway.execute({...call,id:"unknown"},x.context,new AbortController().signal)).rejects.toMatchObject({code:"TOOL_UNRESOLVED"});});
test("invalid paths/text/extra Docker options never create an approval",async()=>{const x=await fixture({importSource:false});for(const args of [{path:"../outside",text:"x"},{path:"big",text:"中".repeat(65536)},{path:"ok",text:"x",hostPath:"/tmp"}])await expect(x.gateway.execute({id:JSON.stringify(args).slice(0,30),name:"workspace_write",arguments:JSON.stringify(args)},x.context,new AbortController().signal)).rejects.toMatchObject({code:"INVALID_INPUT"});expect(x.events).toEqual([]);});
test("the Windows unsupported branch stays fail-closed without requiring native import for parameter validation",async()=>{const descriptor=Object.getOwnPropertyDescriptor(process,"platform")!;try{Object.defineProperty(process,"platform",{value:"win32"});const x=await fixture({importSource:false});for(const args of [{path:"../outside",text:"x"},{path:"ok",text:"x",hostPath:"C:/outside"}])await expect(x.gateway.execute({id:"invalid",name:"workspace_write",arguments:JSON.stringify(args)},x.context,new AbortController().signal)).rejects.toMatchObject({code:"INVALID_INPUT"});await expect(x.files.scan(x.source,{maxEntries:10000,maxFileBytes:100*1024*1024,maxTotalBytes:1024**3})).rejects.toMatchObject({code:"SAFE_FILES_UNAVAILABLE"});expect(x.events).toEqual([]);expect(await readFile(join(x.source,"input.txt"),"utf8")).toBe("源文件");}finally{Object.defineProperty(process,"platform",descriptor);}});
