import { randomUUID } from "node:crypto";
import { mkdir, lstat, open, unlink, statfs, realpath } from "node:fs/promises";
import { join, dirname, basename } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { z } from "zod";
import { AppError, type BackupView, type ExportPreview, type ExportResult, type ExportSelection, type Namespace, type WorkspaceRecord, type WorkspaceDiff } from "../../../../../packages/shared/src/index";
import { namespaceKey, activeStatuses } from "../../../../../packages/storage/src/index";
import type { WorkspaceService } from "./workspace-service";
import type { FileFingerprint, RootIdentity } from "../files/safe-file-ops";
import { excerpt,decodeExcerpt } from "../files/attachment-service";
import { assertWorkspaceRoot, safeRelativePath, assertNoPathCollisions } from "../files/path-policy";
export type ExportOptions={workspace:WorkspaceService;directory:string;principal:()=>Namespace;pickDirectory:()=>Promise<string|null>;confirm:(kind:"write"|"delete"|"export"|"restore"|"remove_backups",paths:string[])=>Promise<boolean>;maxBackupBytes?:number;credentialRoots?:string[]};
type Token={n:string;w:WorkspaceRecord;root:string;identity:RootIdentity;changes:WorkspaceDiff[];expected:Map<string,FileFingerprint|null>;expires:number};
const identity=z.strictObject({device:z.string().regex(/^\d+$/),inode:z.string().regex(/^\d+$/)});
const fingerprint=identity.extend({sha256:z.string().regex(/^[a-f0-9]{64}$/),size:z.number().int().min(0).max(100*1024*1024),mtimeNs:z.string().regex(/^-?\d+$/),mode:z.number().int().min(0).max(0o777).optional()});
const backupSchema=z.strictObject({id:z.string().uuid(),namespaceKey:z.string().max(2048),workspaceId:z.string().uuid(),sessionId:z.string().max(512),path:z.string().max(1024),root:z.string().startsWith("/").max(8192),rootIdentity:identity,blobIdentity:identity,before:fingerprint,after:fingerprint.nullable(),createdAt:z.number().int().nonnegative(),ready:z.boolean()});
type Backup=z.infer<typeof backupSchema>;
const equal=(a:FileFingerprint|null,b:FileFingerprint|null)=>a===null?b===null:b!==null&&Object.keys(a).every(k=>a[k as keyof FileFingerprint]===b[k as keyof FileFingerprint]);
const sameBytes=(a:FileFingerprint|null,b:{sha256:string;size:number}|null)=>a===null?b===null:b!==null&&a.sha256===b.sha256&&a.size===b.size;
const result=(path:string,status:ExportResult["status"],backupId:string|null=null,errorCode:string|null=null):ExportResult=>({path,status,backupId,errorCode});
export class ExportService {
  private tokens=new Map<string,Token>();private db?:DatabaseSync;private initializing?:Promise<DatabaseSync>;private quota:number;private closed=false;
  constructor(private o:ExportOptions){this.quota=o.maxBackupBytes??1024**3;if(!Number.isSafeInteger(this.quota)||this.quota<0||this.quota>1024**3)throw new AppError("INVALID_INPUT","备份上限不得超过 1 GiB");}
  private principal(n:Namespace):void{if(this.closed)throw new AppError("CANCELLED","文件导出服务已关闭");if(namespaceKey(n)!==namespaceKey(this.o.principal()))throw new AppError("PERMISSION_DENIED","当前身份已失效");}
  revokeSession(n:Namespace,sid:string):void{for(const [id,t]of this.tokens)if(t.n===namespaceKey(n)&&t.w.sessionId===sid)this.tokens.delete(id);}
  shutdown():void{this.closed=true;this.tokens.clear();}
  private current(n:Namespace,sid:string):WorkspaceRecord{this.principal(n);this.o.workspace.assertIdle(n,sid);const w=this.o.workspace.snapshots.store.workspaces.getForSession(n,sid);if(!w)throw new AppError("NOT_FOUND","工作区未创建");return w;}
  private validate(n:Namespace,w:WorkspaceRecord):void{this.current(n,w.sessionId);this.o.workspace.snapshots.validate(n,w);}
  private paths(paths:string[]):string[]{if(!Array.isArray(paths)||!paths.length||paths.length>1000)throw new AppError("INVALID_INPUT","请选择 1–1000 个文件");paths.forEach(safeRelativePath);if(new Set(paths).size!==paths.length)throw new AppError("INVALID_INPUT","文件不可重复");assertNoPathCollisions(paths);return paths;}
  private async root(root:string,expected?:RootIdentity):Promise<RootIdentity>{const s=await lstat(root,{bigint:true});if(!s.isDirectory()||s.isSymbolicLink())throw new AppError("UNSAFE_PATH","目标必须是普通目录");const actual={device:String(s.dev),inode:String(s.ino)};if(expected&&(actual.device!==expected.device||actual.inode!==expected.inode))throw new AppError("SOURCE_CHANGED","原目录已被替换");return actual;}
  private async catalog():Promise<DatabaseSync>{if(this.db)return this.db;if(!this.initializing)this.initializing=(async()=>{await mkdir(this.o.directory,{recursive:true,mode:0o700});await this.root(this.o.directory);this.o.directory=await realpath(this.o.directory);await mkdir(join(this.o.directory,"files"),{mode:0o700}).catch(e=>{if(e.code!=="EEXIST")throw e;});await this.root(join(this.o.directory,"files"));const path=join(this.o.directory,"backups.sqlite");await lstat(path).then(s=>{if(!s.isFile()||s.isSymbolicLink()||s.nlink!==1)throw new AppError("UNSAFE_PATH","备份目录无效");},e=>{if(e.code!=="ENOENT")throw e;});const db=new DatabaseSync(path);db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS backups(id TEXT PRIMARY KEY, namespace_key TEXT NOT NULL, workspace_id TEXT NOT NULL, size INTEGER NOT NULL, data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS source_versions(namespace_key TEXT NOT NULL,workspace_id TEXT NOT NULL,root TEXT NOT NULL,device TEXT NOT NULL,inode TEXT NOT NULL,path TEXT NOT NULL,data TEXT NOT NULL,PRIMARY KEY(namespace_key,workspace_id,root,device,inode,path));");this.db=db;return db;})();return this.initializing;}
  dispose():void{this.db?.close();this.db=undefined;this.initializing=undefined;this.tokens.clear();}
  private async save(b:Backup):Promise<void>{backupSchema.parse(b);(await this.catalog()).prepare("INSERT INTO backups VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data").run(b.id,b.namespaceKey,b.workspaceId,b.before.size,JSON.stringify(b));}
  private async get(n:Namespace,id:string):Promise<Backup>{this.principal(n);z.string().uuid().parse(id);const row=(await this.catalog()).prepare("SELECT data FROM backups WHERE id=? AND namespace_key=?").get(id,namespaceKey(n));if(!row)throw new AppError("NOT_FOUND","备份不存在或不属于当前身份");const b=backupSchema.parse(JSON.parse(row.data as string));if(b.id!==id||b.namespaceKey!==namespaceKey(n))throw new AppError("PERMISSION_DENIED","备份归属无效");safeRelativePath(b.path);return b;}
  private async blob(b:Backup):Promise<string>{const path=join(this.o.directory,"files",b.id),s=await lstat(path,{bigint:true});if(!s.isFile()||s.isSymbolicLink()||s.nlink!==1n||String(s.dev)!==b.blobIdentity.device||String(s.ino)!==b.blobIdentity.inode)throw new AppError("SOURCE_CHANGED","备份文件身份已变化");return path;}
  private backupIdle(n:Namespace,b:Backup):void{this.principal(n);try{if(this.o.workspace.snapshots.store.runs.list(n,b.sessionId).some(r=>activeStatuses.includes(r.status)))throw new AppError("RUN_ACTIVE","运行期间不能恢复或删除备份");}catch(e){if(!(e instanceof AppError&&e.code==="NOT_FOUND"))throw e;}}
  private async accepted(n:Namespace,w:WorkspaceRecord,root:string,rootIdentity:RootIdentity,path:string,actual:FileFingerprint|null,baseline:{sha256:string|null;size:number}|undefined):Promise<boolean>{
    const row=(await this.catalog()).prepare("SELECT data FROM source_versions WHERE namespace_key=? AND workspace_id=? AND root=? AND device=? AND inode=? AND path=?").get(namespaceKey(n),w.id,root,rootIdentity.device,rootIdentity.inode,path);
    return row?equal(actual,fingerprint.nullable().parse(JSON.parse(row.data as string))):sameBytes(actual,baseline?{sha256:baseline.sha256!,size:baseline.size}:null);
  }
  private async remember(n:Namespace,w:WorkspaceRecord,root:string,rootIdentity:RootIdentity,path:string,actual:FileFingerprint|null):Promise<void>{
    fingerprint.nullable().parse(actual);(await this.catalog()).prepare("INSERT INTO source_versions VALUES(?,?,?,?,?,?,?) ON CONFLICT(namespace_key,workspace_id,root,device,inode,path) DO UPDATE SET data=excluded.data").run(namespaceKey(n),w.id,root,rootIdentity.device,rootIdentity.inode,path,JSON.stringify(actual));
  }
  async preview(n:Namespace,sid:string,paths:string[]):Promise<ExportPreview>{this.paths(paths);const w=this.current(n,sid);if(!w.sourceRoot||!w.sourceIdentity)throw new AppError("SOURCE_CHANGED","工作区没有可核验的源目录，请在新会话中选择目录");await this.root(w.sourceRoot,w.sourceIdentity);const all=await this.o.workspace.diff(n,sid),baseline=await this.o.workspace.snapshots.artifacts.manifest(w.baselineKey),checkpoint=await this.o.workspace.snapshots.artifacts.manifest(w.checkpointKey);const changes=paths.map(path=>{const diff=all.find(d=>d.relativePath===path);if(!diff||![baseline,checkpoint].some(m=>m.some(e=>e.relativePath===path&&e.kind==="file")))throw new AppError("INVALID_INPUT","只能写回发生变化的普通文件");return diff;});const expected=new Map<string,FileFingerprint|null>(),conflicts:string[]=[];for(const c of changes){const fp=await this.o.workspace.files.fingerprint(w.sourceRoot,c.relativePath,w.sourceIdentity);expected.set(c.relativePath,fp);const before=baseline.find(e=>e.relativePath===c.relativePath&&e.kind==="file");if(!await this.accepted(n,w,w.sourceRoot,w.sourceIdentity,c.relativePath,fp,before))conflicts.push(c.relativePath);}const textPreviews:ExportPreview["textPreviews"]=[];let budget=1024*1024;
    for(const c of changes){
      if(c.binary){textPreviews.push({relativePath:c.relativePath,binary:true,before:null,after:null});continue;}
      const old=expected.get(c.relativePath)!,next=checkpoint.find(e=>e.relativePath===c.relativePath&&e.kind==="file"),cost=Math.min(old?.size??0,65536)+Math.min(next?.size??0,65536);
      if(cost>budget){textPreviews.push({relativePath:c.relativePath,binary:false,before:null,after:null,omitted:true});continue;}
      budget-=cost;const before=old?decodeExcerpt(await this.o.workspace.files.read(w.sourceRoot,c.relativePath,0,65536),old.size):null,after=next?await excerpt(this.o.workspace.snapshots.artifacts,w.checkpointKey,c.relativePath,next.size):null;
      if(!equal(await this.o.workspace.files.fingerprint(w.sourceRoot,c.relativePath,w.sourceIdentity),old))throw new AppError("SOURCE_CHANGED","文本预览期间源文件已变化，请重新预览");
      textPreviews.push({relativePath:c.relativePath,binary:before?.text===null||after?.text===null,before:before?.text===null?null:before,after:after?.text===null?null:after});
    }
    this.validate(n,w);for(const [id,t]of this.tokens)if(t.expires<=performance.now())this.tokens.delete(id);if(this.tokens.size>=64)throw new AppError("INPUT_LIMIT","待确认写回过多");const token=randomUUID();this.tokens.set(token,{n:namespaceKey(n),w,root:w.sourceRoot,identity:w.sourceIdentity,changes,expected,expires:performance.now()+60000});return {token,changes,conflicts,textPreviews};}
  async apply(n:Namespace,token:string,selections:ExportSelection[]):Promise<ExportResult[]>{this.principal(n);const t=this.tokens.get(token);if(!t||t.n!==namespaceKey(n)||t.expires<=performance.now())throw new AppError("PERMISSION_DENIED","写回预览已失效");this.tokens.delete(token);if(!selections.length||selections.length>1000)throw new AppError("INVALID_INPUT","写回选择无效");this.paths(selections.map(s=>s.path));for(const s of selections){const c=t.changes.find(c=>c.relativePath===s.path);if(!c||!["write","delete","skip"].includes(s.action)||(s.action!=="skip"&&(s.action==="delete")!==(c.kind==="deleted")))throw new AppError("INVALID_INPUT","选择与预览不一致");}return this.o.workspace.snapshots.locked(n,t.w.sessionId,async()=>{this.validate(n,t.w);const writes=selections.filter(s=>s.action==="write"),deletes=selections.filter(s=>s.action==="delete");const writeOK=!writes.length||await this.o.confirm("write",writes.map(s=>join(t.root,s.path))),deleteOK=!deletes.length||await this.o.confirm("delete",deletes.map(s=>join(t.root,s.path)));this.validate(n,t.w);const results:ExportResult[]=[];const baseline=await this.o.workspace.snapshots.artifacts.manifest(t.w.baselineKey);for(const s of selections){if(s.action==="skip"||(s.action==="write"&&!writeOK)||(s.action==="delete"&&!deleteOK)){results.push(result(s.path,"skipped"));continue;}const prior=baseline.find(e=>e.relativePath===s.path&&e.kind==="file"),expected=t.expected.get(s.path)!;if(!await this.accepted(n,t.w,t.root,t.identity,s.path,expected,prior)){results.push(result(s.path,"conflict",null,"FILE_CONFLICT"));continue;}results.push(await this.mutate(n,t.w,t.root,t.identity,s.path,expected,s.action==="delete"?null:join(await this.o.workspace.snapshots.artifacts.localPath(t.w.checkpointKey),s.path)));}return results;});}
  private async reserve(n:Namespace,w:WorkspaceRecord,root:string,rootIdentity:RootIdentity,path:string,before:FileFingerprint):Promise<Backup>{const db=await this.catalog(),sum=db.prepare("SELECT COALESCE(SUM(size),0) AS bytes,COUNT(*) AS count FROM backups WHERE namespace_key=? AND workspace_id=?").get(namespaceKey(n),w.id)!;if(Number(sum.bytes)+before.size>this.quota||Number(sum.count)>=10000)throw new AppError("BACKUP_LIMIT","此工作区备份达到上限，请显式管理旧备份");const free=await statfs(this.o.directory,{bigint:true});if(free.bavail*free.bsize<BigInt(before.size)+64n*1024n*1024n)throw new AppError("DISK_FULL","备份所需磁盘空间不足");const id=randomUUID(),file=await open(join(this.o.directory,"files",id),"wx",0o600);let b:Backup;try{const s=await file.stat({bigint:true});b={id,namespaceKey:namespaceKey(n),workspaceId:w.id,sessionId:w.sessionId,path,root,rootIdentity,blobIdentity:{device:String(s.dev),inode:String(s.ino)},before,after:null,createdAt:Date.now(),ready:false};await file.sync();await this.save(b);}finally{await file.close();}return b;}
  private async mutate(n:Namespace,w:WorkspaceRecord,root:string,rootIdentity:RootIdentity,path:string,expected:FileFingerprint|null,source:string|null,backupOperation=false,restoreMode?:number):Promise<ExportResult>{let b:Backup|undefined;try{if(!backupOperation)this.validate(n,w);else this.principal(n);const current=await this.o.workspace.files.fingerprint(root,path,rootIdentity);if(!equal(current,expected))return result(path,"conflict",null,"FILE_CONFLICT");if(expected)b=await this.reserve(n,w,root,rootIdentity,path,expected);else await this.catalog();if(!backupOperation)this.validate(n,w);else this.principal(n);const opts={expectedRoot:rootIdentity,...(restoreMode===undefined?{}:{restoreMode}),...(b?{backupKey:b.id,backupOwner:b.blobIdentity}:{})};let after:FileFingerprint|null=null;if(source){if(!expected)await this.o.workspace.files.prepareParents(root,path,rootIdentity);after=(await this.o.workspace.files.replace(root,path,source,expected,join(this.o.directory,"files"),opts)).version;}else{if(!expected)return result(path,"conflict",null,"FILE_CONFLICT");await this.o.workspace.files.delete(root,path,expected,join(this.o.directory,"files"),opts);}if(b){b.after=after;b.ready=true;await this.save(b);}await this.remember(n,w,root,rootIdentity,path,after);return result(path,source?"written":"deleted",b?.id??null);}catch(error){let code=error instanceof AppError?error.code:"SAFE_FILES_FAILED";try{const actualNow=await this.o.workspace.files.fingerprint(root,path,rootIdentity),incomingNow=source?await this.o.workspace.files.fingerprint(dirname(source),basename(source)):null;if(sameBytes(actualNow,incomingNow)&&!equal(actualNow,expected)){code="WRITE_APPLIED_NOT_DURABLE";await this.remember(n,w,root,rootIdentity,path,actualNow);}}catch{/* cannot establish whether mutation was applied */}if(b){try{await this.blob(b);const fp=await this.o.workspace.files.fingerprint(join(this.o.directory,"files"),b.id);if(sameBytes(fp,b.before)){const actual=await this.o.workspace.files.fingerprint(root,path,rootIdentity),incoming=source?await this.o.workspace.files.fingerprint(dirname(source),basename(source)):null;if(sameBytes(actual,incoming)&&!equal(actual,expected)){b.after=actual;b.ready=true;await this.save(b);await this.remember(n,w,root,rootIdentity,path,actual);code="WRITE_APPLIED_NOT_DURABLE";}}}catch{/* retain the ownership intent; unverified backups are not restorable */}}return result(path,["FILE_CONFLICT","SOURCE_CHANGED"].includes(code)?"conflict":"failed",b?.id??null,code);}}
  async exportToChosenDirectory(n:Namespace,sid:string,paths:string[]):Promise<ExportResult[]>{this.paths(paths);const w=this.current(n,sid),entries=await this.o.workspace.snapshots.artifacts.manifest(w.checkpointKey);if(paths.some(p=>!entries.some(e=>e.relativePath===p&&e.kind==="file")))throw new AppError("INVALID_INPUT","只能导出选中的普通文件");const chosen=await this.o.pickDirectory();this.validate(n,w);if(!chosen)return paths.map(p=>result(p,"skipped"));const rootIdentity=await this.root(chosen),root=await realpath(chosen);assertWorkspaceRoot(root,this.o.credentialRoots??[]);const expected=new Map<string,FileFingerprint|null>();for(const p of paths)expected.set(p,await this.o.workspace.files.fingerprint(root,p,rootIdentity));return this.o.workspace.snapshots.locked(n,sid,async()=>{if(!await this.o.confirm("export",paths.map(p=>join(root,p))))return paths.map(p=>result(p,"skipped"));this.validate(n,w);const out:ExportResult[]=[];for(const p of paths)out.push(await this.mutate(n,w,root,rootIdentity,p,expected.get(p)!,join(await this.o.workspace.snapshots.artifacts.localPath(w.checkpointKey),p)));return out;});}
  async listBackups(n:Namespace,workspaceId?:string):Promise<BackupView[]>{this.principal(n);if(workspaceId!==undefined)z.string().uuid().parse(workspaceId);const db=await this.catalog(),rows=workspaceId===undefined?db.prepare("SELECT data FROM backups WHERE namespace_key=? ORDER BY id LIMIT 10000").all(namespaceKey(n)):db.prepare("SELECT data FROM backups WHERE namespace_key=? AND workspace_id=? ORDER BY id LIMIT 10000").all(namespaceKey(n),workspaceId);this.principal(n);return rows.map(r=>backupSchema.parse(JSON.parse(r.data as string))).map(b=>({id:b.id,workspaceId:b.workspaceId,name:b.path+(b.ready?"":"（未完成，不可恢复）"),size:b.before.size,createdAt:b.createdAt}));}
  async restoreBackup(n:Namespace,id:string):Promise<ExportResult>{const b=await this.get(n,id);return this.o.workspace.snapshots.locked(n,b.sessionId,async()=>{this.backupIdle(n,b);if(!b.ready)return result(b.path,"failed",id,"BACKUP_INCOMPLETE");let source:string;try{source=await this.blob(b);if(!sameBytes(await this.o.workspace.files.fingerprint(join(this.o.directory,"files"),b.id),b.before))throw new AppError("SOURCE_CHANGED","备份内容已变化");const current=await this.o.workspace.files.fingerprint(b.root,b.path,b.rootIdentity);if(!equal(current,b.after))return result(b.path,"conflict",id,"FILE_CONFLICT");}catch(e){return result(b.path,"failed",id,e instanceof AppError?e.code:"SAFE_FILES_FAILED");}if(!await this.o.confirm("restore",[join(b.root,b.path)]))return result(b.path,"skipped",id);this.backupIdle(n,b);const w={id:b.workspaceId,sessionId:b.sessionId}as WorkspaceRecord;return this.mutate(n,w,b.root,b.rootIdentity,b.path,b.after,source,true,b.before.mode);});}
  async removeBackups(n:Namespace,ids:string[]):Promise<void>{this.principal(n);if(!ids.length||ids.length>1000||new Set(ids).size!==ids.length)throw new AppError("INVALID_INPUT","备份选择无效");const records=await Promise.all(ids.map(id=>this.get(n,id)));records.forEach(b=>this.backupIdle(n,b));if(!await this.o.confirm("remove_backups",records.map(b=>b.path)))return;for(const b of records){this.backupIdle(n,b);await this.blob(b).then(unlink,e=>{if(e.code!=="ENOENT")throw e;});(await this.catalog()).prepare("DELETE FROM backups WHERE id=? AND namespace_key=?").run(b.id,namespaceKey(n));}}
}
