import { useEffect,useRef,useState } from "react";
import type { SpeechView } from "../../../../../packages/shared/src/index";
import { VoiceRecorder,recordingMime } from "./voice-recorder";
type Options={ensureSession():Promise<string>;appendDraft(sid:string,text:string):void;draftText:string;disabled:boolean};
type State="idle"|"starting"|"recording"|"transcribing"|"ready"|"error";
export function useVoiceInput(sessionId:string|null,options:Options){const [state,setState]=useState<State>("idle"),[duration,setDuration]=useState(0),[transcript,setTranscript]=useState(""),[error,setError]=useState(""),[config,setConfig]=useState<SpeechView|null>(null),serial=useRef(0),alive=useRef(true),current=useRef(sessionId),latest=useRef(options),scope=useRef<{sid:string;id:string|null}|null>(null),recorder=useRef<VoiceRecorder|null>(null),started=useRef(0);current.current=sessionId;latest.current=options;
  const cancel=()=>{serial.current++;recorder.current?.cancel();recorder.current=null;const op=scope.current;scope.current=null;if(op?.id)void window.desktop.speech.cancel(op.id).catch(()=>{});if(alive.current){setState("idle");setTranscript("");setDuration(0);setError("");}};
  const refresh=async()=>{const c=await window.desktop.speech.get();if(alive.current)setConfig(c);};
  useEffect(()=>{alive.current=true;void refresh().catch(e=>{if(alive.current)setError(String(e));});return()=>{alive.current=false;cancel();};},[]);
  useEffect(()=>{if(scope.current&&scope.current.sid!==sessionId)cancel();},[sessionId]);
  useEffect(()=>{if(options.disabled&&["starting","recording","transcribing"].includes(state))cancel();},[options.disabled]);
  useEffect(()=>{if(state!=="recording")return;const timer=setInterval(()=>setDuration(Math.floor((performance.now()-started.current)/1000)),1000);return()=>clearInterval(timer);},[state]);
  const start=async()=>{if(latest.current.disabled||["starting","recording","transcribing"].includes(state))return;cancel();const token=serial.current;setState("starting");try{if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined")throw new Error("当前环境不支持麦克风录音");const mime=recordingMime(m=>MediaRecorder.isTypeSupported(m)),sid=current.current??await latest.current.ensureSession();if(token!==serial.current||!alive.current||(current.current!==null&&current.current!==sid))return;scope.current={sid,id:null};const op=await window.desktop.speech.beginCapture(sid);if(token!==serial.current||!alive.current){void window.desktop.speech.cancel(op.operationId).catch(()=>{});return;}scope.current.id=op.operationId;const device=new VoiceRecorder({getUserMedia:c=>navigator.mediaDevices.getUserMedia(c),createRecorder:(stream,c)=>new MediaRecorder(stream,c),onFailure:e=>{if(token!==serial.current||!alive.current)return;cancel();setState("error");setError(e.message);}});recorder.current=device;await device.start(mime);if(token!==serial.current||!alive.current){device.cancel();return;}started.current=performance.now();setDuration(0);setState("recording");}catch(e){if(token===serial.current&&alive.current){cancel();setState("error");setError(String(e).replace(/^Error:\s*/,""));}}};
  const stopAndTranscribe=async()=>{const op=scope.current,device=recorder.current,token=serial.current;if(!op?.id||!device||state!=="recording")return;setState("transcribing");try{const audio=await device.stop();recorder.current=null;if(token!==serial.current||!alive.current)return;const result=await window.desktop.speech.submit({sessionId:op.sid,operationId:op.id,...audio});if(token!==serial.current||!alive.current||current.current!==op.sid||result.operationId!==op.id)return;setTranscript(result.text);setState("ready");}catch(e){if(token===serial.current&&alive.current){cancel();setState("error");setError(String(e));}}};
  const insert=()=>{const op=scope.current;if(!op||current.current!==op.sid||!transcript.trim())return;const next=latest.current.draftText?`${latest.current.draftText}\n${transcript.trim()}`:transcript.trim();if(new TextEncoder().encode(next).length>65536){setError("插入后草稿超过 64 KiB，请缩短文字再插入");return;}latest.current.appendDraft(op.sid,transcript.trim());cancel();};
  return {state,duration,transcript,error,config,active:["starting","recording","transcribing"].includes(state),start,stopAndTranscribe,cancel,insert,refresh,setTranscript};
}
export type VoiceControl=ReturnType<typeof useVoiceInput>;
