export type RecorderOptions={getUserMedia:(constraints:MediaStreamConstraints)=>Promise<MediaStream>;createRecorder:(stream:MediaStream,options:MediaRecorderOptions)=>MediaRecorder;onFailure?:(error:Error)=>void};
const mimes=["audio/webm;codecs=opus","audio/webm","audio/mp4","audio/mp4;codecs=mp4a.40.2"];
export class VoiceRecorder{
  private generation=0;private stream?:MediaStream;private recorder?:MediaRecorder;private chunks:Blob[]=[];private size=0;private timer?:ReturnType<typeof setTimeout>;private failure?:Error;private pendingReject?: (error:Error)=>void;private state:"idle"|"starting"|"recording"|"stopping"="idle";
  constructor(private o:RecorderOptions){}
  async start(mime:string):Promise<void>{if(this.state!=="idle")throw new Error("已有录音");if(!mimes.includes(mime))throw new Error("设备不支持受控录音格式");this.failure=undefined;this.state="starting";const g=++this.generation;let stream:MediaStream|undefined;try{const acquired=this.o.getUserMedia({audio:true,video:false}).then(value=>{if(g!==this.generation)value.getTracks().forEach(t=>t.stop());return value;});stream=await Promise.race([acquired,new Promise<never>((_,reject)=>{this.pendingReject=reject;this.timer=setTimeout(()=>this.fail(new Error("等待麦克风超过 60 秒，请重试或检查系统权限")),60000);})]);if(g===this.generation){this.pendingReject=undefined;if(this.timer)clearTimeout(this.timer);this.timer=undefined;}if(g!==this.generation){stream.getTracks().forEach(t=>t.stop());throw new Error("录音已取消");}if(!stream.getTracks().length||stream.getTracks().some(t=>t.kind!=="audio"))throw new Error("只允许音频输入");this.stream=stream;this.recorder=this.o.createRecorder(stream,{mimeType:mime});const recorder=this.recorder;if(!mimes.includes(recorder.mimeType))throw new Error("录音设备返回了不支持的实际编码");this.chunks=[];this.size=0;recorder.ondataavailable=e=>{if(g!==this.generation||!e.data.size)return;this.size+=e.data.size;if(this.size>20*1024*1024){this.fail(new Error("录音超过 20 MiB，已停止且不会上传"));return;}this.chunks.push(e.data);};recorder.onerror=()=>this.fail(new Error("录音设备发生错误，音轨已释放"));stream.getTracks().forEach(t=>t.addEventListener("ended",()=>{if(g===this.generation&&(this.state==="recording"||this.state==="starting"))this.fail(new Error("录音设备已断开"));},{once:true}));recorder.start(250);this.state="recording";this.timer=setTimeout(()=>this.fail(new Error("录音达到 120 秒，已停止且不会自动上传")),120000);}catch(e){stream?.getTracks().forEach(t=>t.stop());if(g===this.generation)this.cancel();throw e;}}
  private release():void{if(this.timer)clearTimeout(this.timer);this.timer=undefined;this.stream?.getTracks().forEach(t=>t.stop());this.stream=undefined;}
  private fail(error:Error):void{this.failure=error;this.cancel();this.o.onFailure?.(error);}
  async stop():Promise<{mimeType:string;bytes:Uint8Array}>{if(this.failure)throw this.failure;if(this.state!=="recording"||!this.recorder)throw new Error("没有可提交的录音");this.state="stopping";const g=this.generation,recorder=this.recorder,mimeType=recorder.mimeType;return new Promise((resolve,reject)=>{this.pendingReject=reject;recorder.onstop=()=>{this.release();const blob=new Blob(this.chunks,{type:mimeType});this.chunks=[];void blob.arrayBuffer().then(buffer=>{if(g!==this.generation||this.failure)throw this.failure??new Error("录音已取消");if(!buffer.byteLength||buffer.byteLength>20*1024*1024)throw new Error("录音为空或超过上限");this.state="idle";this.pendingReject=undefined;this.recorder=undefined;resolve({mimeType,bytes:new Uint8Array(buffer)});}).catch(e=>{if(g===this.generation){this.state="idle";this.recorder=undefined;this.chunks=[];}this.pendingReject=undefined;reject(e);});};try{recorder.stop();}catch(e){this.fail(e instanceof Error?e:new Error("录音停止失败"));}});}
  cancel():void{++this.generation;this.state="idle";const recorder=this.recorder;this.recorder=undefined;if(recorder){recorder.ondataavailable=null;recorder.onstop=null;recorder.onerror=null;if(recorder.state!=="inactive")try{recorder.stop();}catch{/* release tracks even if device already disappeared */}}this.release();this.chunks=[];this.size=0;this.pendingReject?.(this.failure??new Error("录音已取消"));this.pendingReject=undefined;}
}
export function recordingMime(supports:(mime:string)=>boolean):string{const mime=mimes.find(supports);if(!mime)throw new Error("当前环境不支持 WebM/Opus 或 MP4 录音");return mime;}
