import { randomUUID } from "node:crypto";
import { AppError,speechDraftSchema,type Namespace,type SpeechView,type SpeechDraft,type AudioSubmission,type SpeechConfig } from "../../../../../packages/shared/src/index";
import { namespaceKey,type Store } from "../../../../../packages/storage/src/index";
import { normalizeTranscriptionEndpoint,transcribeAudio,validateAudio } from "../../../../../packages/model-adapter/src/index";
import type { SecretStore } from "../credentials";
export type TranscriptionOptions={store:Store;secrets:SecretStore;principal:()=>Namespace;window:()=>number;transcribe?:(input:{config:SpeechDraft;apiKey:string;audio:AudioSubmission;signal:AbortSignal})=>Promise<string>};
type Operation={id:string;n:Namespace;sessionId:string;owner:number;revision:string;controller:AbortController;submitted:boolean;expires:number;timer:ReturnType<typeof setTimeout>};
const initial:SpeechConfig={enabled:false,name:"语音转写",baseUrl:"https://api.openai.com/v1",modelId:"whisper-1",timeoutMs:120000,allowInsecureHttp:false,credentialRef:null,revision:"unconfigured"};
export class TranscriptionService{
  private operations=new Map<string,Operation>();private closed=false;
  constructor(private o:TranscriptionOptions){}
  private principal(n:Namespace):void{if(this.closed)throw new AppError("CANCELLED","语音服务已关闭");if(namespaceKey(n)!==namespaceKey(this.o.principal()))throw new AppError("PERMISSION_DENIED","当前身份已失效");}
  private config(n:Namespace):SpeechConfig{return this.o.store.transcriptions.get(n)??initial;}
  private view(n:Namespace,c:SpeechConfig):SpeechView{const {credentialRef,revision:_,...draft}=c;return {...draft,credentialState:credentialRef?this.o.secrets.status(credentialRef,n):"missing"};}
  async get(n:Namespace):Promise<SpeechView>{this.principal(n);return this.view(n,this.config(n));}
  async save(n:Namespace,draft:SpeechDraft,apiKey?:string):Promise<SpeechView>{this.principal(n);const value=speechDraftSchema.parse(draft),url=normalizeTranscriptionEndpoint(value.baseUrl);if(url.protocol==="http:"&&!value.allowInsecureHttp)throw new AppError("INVALID_INPUT","明文 HTTP 需要明确许可");if(apiKey!==undefined&&(!apiKey.trim()||apiKey.length>16384||/[\r\n]/.test(apiKey)))throw new AppError("INVALID_INPUT","转写密钥无效");const old=this.config(n),secret=apiKey===undefined?undefined:await this.o.secrets.put(apiKey,n);let next:SpeechConfig;try{this.principal(n);if(this.config(n).revision!==old.revision)throw new AppError("CONFIG_CHANGED","转写配置已变化");next={...value,credentialRef:secret?.ref??old.credentialRef,revision:randomUUID()};this.o.store.transcriptions.save(n,next);for(const op of this.operations.values())if(namespaceKey(op.n)===namespaceKey(n))this.end(op);}catch(e){if(secret)await this.o.secrets.remove(secret.ref,n);throw e;}if(secret&&old.credentialRef)await this.o.secrets.remove(old.credentialRef,n);this.principal(n);return this.view(n,next);}
  async begin(n:Namespace,sid:string,owner:number):Promise<{operationId:string}>{this.principal(n);this.o.store.sessions.get(n,sid);if(owner!==this.o.window())throw new AppError("PERMISSION_DENIED","录音窗口已变化");const c=this.config(n);if(!c.enabled)throw new AppError("ASR_DISABLED","请先启用独立语音转写配置");if(!c.credentialRef||this.o.secrets.status(c.credentialRef,n)==="missing")throw new AppError("CREDENTIAL_REQUIRED","请填写转写服务的 API Key");for(const op of this.operations.values())if(op.owner===owner)throw new AppError("AUDIO_BUSY","此窗口已有录音或转写操作");const id=randomUUID(),lifetime=120000+c.timeoutMs+30000,op:Operation={id,n:{...n},sessionId:sid,owner,revision:c.revision,controller:new AbortController(),submitted:false,expires:performance.now()+lifetime,timer:setTimeout(()=>{const op=this.operations.get(id);if(op)this.end(op);},lifetime)};op.timer.unref?.();this.operations.set(id,op);return {operationId:id};}
  private check(n:Namespace,op:Operation):SpeechConfig{this.principal(n);if(this.operations.get(op.id)!==op||op.controller.signal.aborted||op.expires<=performance.now()||op.owner!==this.o.window()||namespaceKey(op.n)!==namespaceKey(n))throw new AppError("PERMISSION_DENIED","录音操作已失效");this.o.store.sessions.get(n,op.sessionId);const c=this.config(n);if(c.revision!==op.revision||!c.enabled)throw new AppError("CONFIG_CHANGED","转写配置已变化");return c;}
  async submit(n:Namespace,audio:AudioSubmission):Promise<{operationId:string;text:string}>{this.principal(n);const op=this.operations.get(audio.operationId);if(!op||op.submitted||op.sessionId!==audio.sessionId)throw new AppError("PERMISSION_DENIED","转写操作不存在或已经使用");const c=this.check(n,op);validateAudio(audio);op.submitted=true;try{const apiKey=c.credentialRef?await this.o.secrets.get(c.credentialRef,n):null;this.check(n,op);if(apiKey===null)throw new AppError("CREDENTIAL_REQUIRED","请重新填写转写 API Key");const {credentialRef:_,revision:__,...requestConfig}=c;const text=await (this.o.transcribe??transcribeAudio)({config:requestConfig,apiKey,audio,signal:op.controller.signal});this.check(n,op);if(!text.trim()||Buffer.byteLength(text)>65536)throw new AppError("ASR_PROTOCOL_ERROR","转写文字无效或超过上限");return {operationId:op.id,text};}finally{this.end(op);}}
  private end(op:Operation):void{op.controller.abort();clearTimeout(op.timer);this.operations.delete(op.id);}
  cancel(n:Namespace,id:string):void{this.principal(n);const op=this.operations.get(id);if(op&&namespaceKey(op.n)===namespaceKey(n))this.end(op);}
  cancelSession(n:Namespace,sid:string):void{for(const op of this.operations.values())if(namespaceKey(op.n)===namespaceKey(n)&&op.sessionId===sid)this.end(op);}
  cancelNamespace(n:Namespace):void{for(const op of this.operations.values())if(namespaceKey(op.n)===namespaceKey(n))this.end(op);}
  shutdown():void{this.closed=true;for(const op of this.operations.values())this.end(op);}
}
