import { AppError,namespaceSchema,type Namespace } from "../../../../packages/shared/src/index";
import { activeStatuses,namespaceKey,type Store } from "../../../../packages/storage/src/index";
import type { AgentService } from "./agent-service";
import type { WorkerSupervisor } from "./worker-supervisor";
import type { createFeatureServices } from "./feature-services";
import type { MediaPermissionService } from "./speech/media-permissions";
export type LifecycleOptions={store:Store;agents:AgentService;supervisor:WorkerSupervisor;features:ReturnType<typeof createFeatureServices>;media:MediaPermissionService;principal:()=>Namespace;ownsInstance:()=>boolean;timeoutMs?:number};
export class SessionLifecycle{
 private closed=false;private removing=new Map<string,Promise<void>>();private quit?:Promise<void>;
 constructor(private o:LifecycleOptions){o.agents.configureLifecycle((n,sid)=>{if(this.closed)throw new AppError("CANCELLED","应用正在退出");o.features.snapshots.assertStartAllowed(n,sid);},id=>o.features.sandbox.cancel(id));}
 private owner():void{if(!this.o.ownsInstance())throw new AppError("INSTANCE_NOT_OWNER","仅主实例可清理资源");}
 private access(n:Namespace):void{this.owner();if(this.closed)throw new AppError("CANCELLED","应用正在退出");if(namespaceKey(n)!==namespaceKey(this.o.principal()))throw new AppError("PERMISSION_DENIED","当前身份已失效");}
 private decode(key:string):Namespace{const [instanceId,accountId,teamId]=JSON.parse(key);return namespaceSchema.parse({instanceId,accountId,teamId});}
 private retained():Set<string>{return new Set([...this.o.store.workspaces.retainedSnapshotKeys(),...this.o.store.attachments.retainedSnapshotKeys()]);}
 private async bounded(work:Promise<unknown>):Promise<void>{let timer:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([work,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new AppError("RESOURCE_CLEANUP_PENDING","资源停止尚未确认，记录和归属信息已保留，请稍后重试")),Math.min(10000,Math.max(10,this.o.timeoutMs??10000)));})]);}finally{if(timer)clearTimeout(timer);}}
 private revoke(n:Namespace,sid:string):string[]{const f=this.o.features;f.snapshots.retire(n,sid);f.grants.revokeSession(n,sid);f.workspaces.revokeSession(n,sid);f.exports.revokeSession(n,sid);this.o.media.revokeSession(n,sid);f.speech.cancelSession(n,sid);const runs=this.o.store.runs.list(n,sid);for(const r of runs)f.approvals.revokeRun(n,r.id);return runs.map(r=>r.id);}
 private async stop(n:Namespace,sid:string,ids:string[]):Promise<void>{await Promise.all(ids.map(id=>this.o.agents.cancel(n,id)));await this.bounded(Promise.all([this.o.supervisor.waitFor(ids),this.o.features.sandbox.stopSession(namespaceKey(n),sid),this.o.features.snapshots.drain(n,sid)]));if(this.o.store.runs.list(n,sid).some(r=>activeStatuses.includes(r.status)))throw new AppError("RESOURCE_CLEANUP_PENDING","运行尚未停止，会话数据已保留");await this.o.features.workspaces.discardSessionCheckouts(n,sid);}
 async remove(n:Namespace,sid:string):Promise<void>{this.access(n);this.o.store.sessions.get(n,sid);const key=namespaceKey(n)+sid,previous=this.removing.get(key);if(previous)return previous;const work=(async()=>{const w=this.o.store.workspaces.getForSession(n,sid),keys=new Set([...(w?[w.baselineKey,w.checkpointKey]:[]),...this.o.store.attachments.list(n,sid).map(a=>a.snapshotKey)]),ids=this.revoke(n,sid);await this.stop(n,sid,ids);this.access(n);this.o.store.sessions.remove(n,sid);const retained=this.retained();for(const key of keys)if(!retained.has(key))await this.o.features.artifacts.discard(key).catch(()=>{/* ownership record remains for startup retry */});})();this.removing.set(key,work);try{await work;}finally{if(this.removing.get(key)===work)this.removing.delete(key);}}
 async revokeNamespace(n:Namespace):Promise<void>{this.access(n);const sessions=this.o.store.sessions.list(n);const scopes=sessions.map(s=>({sid:s.id,ids:this.revoke(n,s.id)}));await this.o.agents.cancelNamespace(n);await this.bounded(Promise.all(scopes.map(s=>this.stop(n,s.sid,s.ids))));for(const s of sessions)this.o.features.snapshots.resume(n,s.id);}
 async recover():Promise<void>{this.owner();if(this.closed)throw new AppError("CANCELLED","应用正在退出");this.o.store.runs.recoverInterrupted();await this.o.features.sandbox.cleanupOwned().catch(()=>{/* durable Docker ownership keeps deletion authority narrow and blocks new commands */});await this.o.features.artifacts.collect(this.retained());}
 shutdown():Promise<void>{this.owner();if(this.quit)return this.quit;this.closed=true;this.o.agents.beginShutdown();const f=this.o.features;f.imagePreparation.controller?.abort();this.o.media.shutdown();f.speech.shutdown();f.grants.clear();f.exports.shutdown();f.snapshots.close();const all=this.o.store.sessions.all(),namespaces=new Map<string,Namespace>();for(const s of all){const n=this.decode(s.namespaceKey);namespaces.set(s.namespaceKey,n);this.revoke(n,s.id);}this.quit=(async()=>{await Promise.all([...namespaces.values()].map(n=>this.o.agents.cancelNamespace(n)));await this.bounded(Promise.all([this.o.supervisor.shutdown(),f.sandbox.shutdown(),f.snapshots.drain(),f.imagePreparation.promise??Promise.resolve(),...this.removing.values()]));})();return this.quit;}
}
