import { afterEach, expect, test, vi } from "vitest";
import { PassThrough, Readable } from "node:stream";
import { writeFile, readdir, readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { fileFixture } from "../../../apps/desktop/tests/file-feature-fixture";
import { ImageService } from "../src/image-service";
import { DockerSandboxProvider } from "../src/docker-provider";
import type { DockerExecutor, DockerProcess } from "../src/docker-client";
import type { AgentEvent } from "../../shared/src/index";
const cleanup:(()=>Promise<void>)[]=[];afterEach(async()=>{vi.restoreAllMocks();for(const fn of cleanup.splice(0).reverse())await fn();});
const imageId="sha256:"+"b".repeat(64),containerId="c".repeat(64);
test.skipIf(process.platform==="win32")("session cancellation removes its queued command without disturbing other occupied queue slots",async()=>{const x=await fixture();let release!:()=>void;const gate=new Promise<void>(r=>{release=r;});x.client.assertLocal=()=>gate;const a=new AbortController(),b=new AbortController(),first=x.provider.execute({...x.input,owner:{...x.input.owner,sessionId:"other-a",runId:"other-a"},signal:a.signal}),second=x.provider.execute({...x.input,owner:{...x.input.owner,sessionId:"other-b",runId:"other-b"},signal:b.signal}),queued=x.provider.execute(x.input);await x.provider.stopSession(x.input.owner.namespaceKey,x.input.owner.sessionId);expect((await queued).reason).toBe("cancelled");expect(x.client.starts).toBe(0);a.abort();b.abort();release();await Promise.all([first,second]);expect(x.client.live.size).toBe(0);});
test.skipIf(process.platform==="win32")("session cleanup refuses mismatched container ownership and preserves its retry record",async()=>{const x=await fixture();x.client.foreign=true;await x.provider.execute(x.input);await expect(async()=>x.provider.stopSession(x.input.owner.namespaceKey,x.input.owner.sessionId)).rejects.toMatchObject({code:"RESOURCE_CLEANUP_PENDING"});expect(x.client.calls.filter(c=>c[0]==="rm")).toEqual([]);expect((await readdir(join(x.state,"owners"))).filter(p=>p.endsWith(".json"))).toHaveLength(1);x.client.foreign=false;await x.provider.stopSession(x.input.owner.namespaceKey,x.input.owner.sessionId);expect(x.client.live.size).toBe(0);});
const info={ID:"engine-local",OSType:"linux",CgroupVersion:"2",MemoryLimit:true,SwapLimit:true,PidsLimit:true,CpuCfsQuota:true,SecurityOptions:["name=seccomp,profile=builtin","name=cgroupns"]};
export function isolation(owner:string){return {Id:containerId,Name:`/fastgpt-${owner}`,Image:imageId,State:{Running:true,OOMKilled:false},Mounts:[],Config:{User:"1000:1000",WorkingDir:"/workspace",Labels:{"org.fastgpt.desktop.owner":owner},Env:["HOME=/tmp","LANG=C.UTF-8","PATH=/usr/local/bin:/usr/bin:/bin","PYTHONDONTWRITEBYTECODE=1","NODE_VERSION=22.0.0","YARN_VERSION=1.22.0",...["HTTP_PROXY","HTTPS_PROXY","ALL_PROXY","NO_PROXY","FTP_PROXY","http_proxy","https_proxy","all_proxy","no_proxy","ftp_proxy"].map(k=>`${k}=`)]},HostConfig:{NetworkMode:"none",ReadonlyRootfs:true,CapDrop:["ALL"],CapAdd:null,SecurityOpt:["no-new-privileges:true"],Memory:1073741824,MemorySwap:1073741824,PidsLimit:128,NanoCpus:2000000000,CgroupnsMode:"private",IpcMode:"private",PidMode:"",Init:true,Binds:null,Devices:[],DeviceRequests:null,PortBindings:{},PublishAllPorts:false,Privileged:false,LogConfig:{Type:"none"},Tmpfs:{"/workspace":"rw,nosuid,nodev,size=1073741824,nr_inodes=16384,mode=0700,uid=1000,gid=1000","/tmp":"rw,nosuid,nodev,noexec,size=67108864,nr_inodes=4096,mode=1777"}}};}
export function probe(oom=0){return {uid:1000,gid:1000,noNewPrivs:1,seccomp:2,memoryMax:1073741824,swapMax:0,pidsMax:128,cpuQuota:200000,cpuPeriod:100000,oomKills:oom,workspace:{bytes:1073741824,inodes:16384,nodev:true,nosuid:true},tmp:{bytes:67108864,inodes:4096,nodev:true,nosuid:true,noexec:true},rootReadonly:true,pids:{"1":"100","7":"101"},selfPid:21};}
class ExternalDocker implements DockerExecutor {
  owner="";source="";calls:string[][]=[];starts=0;command=false;bad=false;oom=0;containerOom=false;output:Buffer[]=[Buffer.from("中").subarray(0,1),Buffer.from("中").subarray(1),Buffer.from("\u001b[31m文\u001b[0m\u0000\n")];stall=false;exitCode=0;engine="engine-local";foreign=false;changeEngine=false;extraPid=false;failCleanup=false;live=new Map<string,string>();
  async assertLocal(){}
  async run(args:string[]){this.calls.push(args);let stdout="";
    if(args[0]==="info")stdout=JSON.stringify({...info,ID:this.engine});
    else if(args[0]==="image")stdout=JSON.stringify([{Id:imageId,Config:{Env:[],User:"1000:1000",WorkingDir:"/workspace",Labels:{"org.fastgpt.desktop.source":this.source}}}]);
    else if(args[0]==="create"){this.owner=args[args.indexOf("--label")+1].split("=")[1];stdout=containerId;this.live.set(containerId,this.owner);}
    else if(args[0]==="inspect"){const data=isolation(this.owner);if(this.bad)data.HostConfig.NetworkMode="bridge";if(this.command&&this.containerOom){data.State.Running=false;data.State.OOMKilled=true;}if(this.foreign)data.Config.Labels["org.fastgpt.desktop.owner"]=randomUUID();stdout=JSON.stringify([data]);}
    else if(args[0]==="ps")stdout=this.live.has(containerId)?containerId:"";
    else if(args[0]==="rm"){if(this.failCleanup)return {stdout:"",stderr:"deletion failed",code:1};this.live.delete(containerId);}
    else if(args.includes("probe")){const data=probe(this.command?this.oom:0);if(this.command&&this.extraPid)(data.pids as Record<string,string>)["99"]="199";stdout=JSON.stringify(data);}
    if(args.includes("probe")&&this.command&&this.containerOom)return {stdout:"",stderr:"container stopped",code:1};
    return {stdout,stderr:"",code:0};
  }
  async start(args:string[],options?:{signal?:AbortSignal}):Promise<DockerProcess>{this.calls.push(args);
    if(args[0]==="build"){this.source=args[args.indexOf("--label")+1].split("=")[1];await writeFile(args[args.indexOf("--iidfile")+1],imageId);return this.process([]);}
    if(args.includes("import")){const input=new PassThrough();void(async()=>{for await(const _ of input){/* external transport sink */}})();return {...this.process([]),stdin:input};}
    if(args.includes("export")){const json=Buffer.from('{"type":"end"}'),size=Buffer.alloc(4);size.writeUInt32BE(json.length);return this.process([Buffer.concat([size,json])]);}
    if(args.includes("command")){this.command=true;this.starts++;if(this.changeEngine)this.engine="recreated-engine";return this.process(this.output,this.stall,options?.signal,this.exitCode);}
    throw new Error("Unexpected Docker external request");
  }
  private process(output:Buffer[],stall=false,signal?:AbortSignal,code=0):DockerProcess{const stdout=stall?new PassThrough():Readable.from(output),stderr=Readable.from([]);let finish:(result:{code:number|null;signal:NodeJS.Signals|null})=>void=()=>{};
    const ended=stall?new Promise<{code:number|null;signal:NodeJS.Signals|null}>(r=>{finish=r;}):Promise.resolve({code,signal:null});const kill=()=>{stdout.destroy();finish({code:null,signal:"SIGKILL"});};signal?.addEventListener("abort",kill,{once:true});if(signal?.aborted)kill();return {stdin:new PassThrough(),stdout,stderr,wait:()=>ended,kill};}
}
async function fixture(){const x=await fileFixture();cleanup.push(x.cleanup);const client=new ExternalDocker(),state=join(x.root,"sandbox"),images=new ImageService({client,assetDirectory:resolve("packages/sandbox/image"),stateDirectory:join(state,"image")});await images.prepare(new AbortController().signal,()=>{});const provider=new DockerSandboxProvider({client,images,files:x.artifacts,stateDirectory:join(state,"owners")});cleanup.push(()=>provider.shutdown());const key=await x.artifacts.createSnapshot();await x.artifacts.write(key,"note.txt",(async function*(){yield Buffer.from("input");})());const events:AgentEvent[]=[];
  const input={owner:{namespaceKey:"n",sessionId:randomUUID(),runId:randomUUID(),callId:randomUUID()},snapshotKey:key,command:"printf '中文'",cwd:".",signal:new AbortController().signal,onEvent:async(e:AgentEvent)=>{events.push(e);}};return {...x,client,provider,input,events,state};}
test.skipIf(process.platform==="win32")("executes only proved isolation, consumes input before returning verified output and streams decoded plain text",async()=>{const x=await fixture();expect(await x.provider.detect()).toEqual({available:true,reason:null,imageReady:true});const result=await x.provider.execute(x.input);expect(result.reason).toBe("exited");expect(result.snapshotKey).not.toBeNull();expect(result.snapshotKey).not.toBe(x.input.snapshotKey);await expect(x.artifacts.localPath(x.input.snapshotKey)).rejects.toMatchObject({code:"NOT_FOUND"});expect(await x.artifacts.manifest(result.snapshotKey!)).toEqual([]);expect(x.events.filter(e=>e.type==="command_output").map(e=>e.text).join("")).toBe("中文\n");expect(x.events[0]?.type).toBe("command_started");expect(x.events.at(-1)?.type).toBe("command_finished");expect(x.client.live.size).toBe(0);expect(await readdir(join(x.state,"owners"))).toEqual([]);});
test.skipIf(process.platform==="win32")("refuses an unproved network configuration before starting any untrusted command",async()=>{const x=await fixture();x.client.bad=true;const result=await x.provider.execute(x.input);expect(result.snapshotKey).toBeNull();expect(x.client.starts).toBe(0);expect(x.events).toEqual([]);expect(x.client.live.size).toBe(0);});
test.skipIf(process.platform==="win32")("combined raw/rendered output is bounded and kills the whole container without a snapshot",async()=>{const x=await fixture();x.client.output=[Buffer.alloc(1024*1024+1,120)];const result=await x.provider.execute(x.input);expect(result.reason).toBe("output_limit");expect(result.truncated).toBe(true);expect(result.snapshotKey).toBeNull();const text=x.events.filter(e=>e.type==="command_output").map(e=>e.text).join("");expect(Buffer.byteLength(text)).toBe(1024*1024);expect(x.client.calls.some(c=>c[0]==="kill"&&c.includes(containerId))).toBe(true);expect(x.client.live.size).toBe(0);});
test.skipIf(process.platform==="win32")("cancel aborts stalled output and removes the owned container",async()=>{const x=await fixture();x.client.stall=true;const abort=new AbortController(),run=x.provider.execute({...x.input,signal:abort.signal});for(let i=0;i<100&&!x.client.starts;i++)await new Promise(r=>setTimeout(r,2));expect(x.client.starts).toBe(1);abort.abort();const result=await run;expect(result.reason).toBe("cancelled");expect(result.snapshotKey).toBeNull();expect(x.client.live.size).toBe(0);});
test.skipIf(process.platform==="win32")("nonzero exit keeps verified artifacts but a cgroup OOM event never does",async()=>{const x=await fixture();x.client.exitCode=3;const result=await x.provider.execute(x.input);expect(result.reason).toBe("exited");expect(result.exitCode).toBe(3);expect(result.snapshotKey).not.toBeNull();const y=await fixture();y.client.oom=1;const killed=await y.provider.execute(y.input);expect(killed.reason).toBe("oom");expect(killed.snapshotKey).toBeNull();expect(y.client.calls.some(c=>c[0]==="kill")).toBe(true);});
test.skipIf(process.platform==="win32")("cleanup never removes a foreign label or loses ownership metadata on a different engine",async()=>{const x=await fixture();x.client.foreign=true;await x.provider.execute(x.input);expect(x.client.calls.filter(c=>c[0]==="rm")).toEqual([]);expect(x.client.live.size).toBe(1);const records=await readdir(join(x.state,"owners"));expect(records.filter(p=>p.endsWith(".json"))).toHaveLength(1);const original=await readFile(join(x.state,"owners",records[0]),"utf8");x.client.foreign=false;x.client.engine="another-engine";await x.provider.cleanupOwned();expect(x.client.live.size).toBe(1);expect(await readFile(join(x.state,"owners",records[0]),"utf8")).toBe(original);x.client.engine="engine-local";await x.provider.cleanupOwned();expect(x.client.live.size).toBe(0);});
test.skipIf(process.platform==="win32")("engine replacement during execution cannot grant kill/removal on the replacement engine",async()=>{const x=await fixture();x.client.changeEngine=true;const result=await x.provider.execute(x.input);expect(result.snapshotKey).toBeNull();expect(x.client.calls.filter(c=>c[0]==="rm"||c[0]==="kill")).toEqual([]);expect(x.client.live.size).toBe(1);x.client.changeEngine=false;x.client.engine="engine-local";await x.provider.cleanupOwned();});
test.skipIf(process.platform==="win32")("the exact 120-second deadline kills stalled execution and freezes a monotonic terminal duration",async()=>{const x=await fixture();x.client.stall=true;const realTimer=globalThis.setTimeout,requested:number[]=[];vi.spyOn(globalThis,"setTimeout").mockImplementation(((callback:()=>void,ms:number,...args:unknown[])=>{requested.push(ms);return realTimer(callback,ms===120000?20:ms,...args);}) as typeof setTimeout);const result=await x.provider.execute(x.input);expect(requested).toContain(120000);expect(result.reason).toBe("timeout");expect(result.snapshotKey).toBeNull();expect(result.elapsedMs).toBeGreaterThan(0);const first=x.provider.timing(x.input.owner.runId,x.input.owner.callId);await new Promise(r=>realTimer(r,10));expect(x.provider.timing(x.input.owner.runId,x.input.owner.callId)).toEqual(first);expect(first.active).toBe(false);expect(x.client.calls.some(c=>c[0]==="kill")).toBe(true);});
test.skipIf(process.platform==="win32")("unconfirmed background processes refuse artifact export",async()=>{const x=await fixture();x.client.extraPid=true;const result=await x.provider.execute(x.input);expect(result.reason).toBe("failed");expect(result.snapshotKey).toBeNull();expect(x.client.calls.some(c=>c.includes("export"))).toBe(false);});
test.skipIf(process.platform==="win32")("OOM-killed PID1 reports OOM even though an active cgroup probe is no longer possible",async()=>{const x=await fixture();x.client.containerOom=true;const result=await x.provider.execute(x.input);expect(result.reason).toBe("oom");expect(result.snapshotKey).toBeNull();});
test.skipIf(process.platform==="win32")("failed finish persistence does not leak an undisclosed output snapshot",async()=>{const x=await fixture();await expect(x.provider.execute({...x.input,onEvent:async e=>{if(e.type==="command_finished")throw new Error("storage unavailable");}})).rejects.toThrow("storage unavailable");expect(await readdir(join(x.root,"artifacts",".owners"))).toEqual([]);});
test.skipIf(process.platform==="win32")("shared-contract-sized namespace and call IDs remain ownable and cleanable",async()=>{const x=await fixture();const result=await x.provider.execute({...x.input,owner:{...x.input.owner,namespaceKey:"n".repeat(1024),callId:"c".repeat(512)}});expect(result.reason).toBe("exited");expect(x.client.live.size).toBe(0);expect(await readdir(join(x.state,"owners"))).toEqual([]);});
test.skipIf(process.platform==="win32")("runtime cleanup failure blocks new commands until verified owned cleanup succeeds",async()=>{const x=await fixture();x.client.failCleanup=true;expect((await x.provider.execute(x.input)).reason).toBe("failed");expect(await x.provider.detect()).toMatchObject({available:false,reason:"RESOURCE_CLEANUP_PENDING"});await expect(x.provider.execute({...x.input,owner:{...x.input.owner,callId:"new-call"}})).rejects.toMatchObject({code:"RESOURCE_CLEANUP_PENDING"});expect(x.client.starts).toBe(1);expect((await readdir(join(x.state,"owners"))).filter(f=>f.endsWith(".json"))).toHaveLength(1);x.client.failCleanup=false;await x.provider.cleanupOwned();expect((await x.provider.detect()).available).toBe(true);expect(x.client.live.size).toBe(0);});
test.skipIf(process.platform==="win32")("queued and still-preparing commands do not start after runtime cleanup failure",async()=>{const x=await fixture();x.client.failCleanup=true;let release!:()=>void,releaseOther!:()=>void;const gate=new Promise<void>(r=>release=r),otherGate=new Promise<void>(r=>releaseOther=r);const first=x.provider.execute({...x.input,onEvent:async e=>{if(e.type==="command_started")await gate;}});for(let i=0;i<100&&!x.client.starts;i++)await new Promise(r=>setTimeout(r,2));let held=false;x.client.assertLocal=async()=>{if(!held){held=true;await otherGate;}};const other=x.provider.execute({...x.input,owner:{...x.input.owner,callId:"preparing"}}),queued=x.provider.execute({...x.input,owner:{...x.input.owner,callId:"queued"}}).catch(e=>e);try{release();expect((await first).reason).toBe("failed");expect(await queued).toMatchObject({code:"RESOURCE_CLEANUP_PENDING"});expect(x.client.starts).toBe(1);}finally{release();releaseOther();expect(await other.catch(e=>e)).toMatchObject({code:"RESOURCE_CLEANUP_PENDING"});}expect(x.client.starts).toBe(1);});
