import { AppError, approvalRequestSchema, type AgentEvent, type ApprovalDecision, type ApprovalRequestView, type Namespace, type ToolCall, type ToolContext } from "../../../../../packages/shared/src/index";
import { namespaceKey, type Store } from "../../../../../packages/storage/src/index";
import { createHash, randomUUID } from "node:crypto";
export type ApprovalOptions={store:Store;principal:()=>Namespace;persistEvent:(context:ToolContext,event:AgentEvent)=>Promise<void>};
export function canonicalArguments(raw:string):string {
  let value:unknown;try{if(Buffer.byteLength(raw)>1024*1024)throw new Error();value=JSON.parse(raw);}catch{throw new AppError("INVALID_INPUT","工具参数不是有界 JSON");}
  function sort(v:unknown,depth=0):unknown {if(depth>32)throw new AppError("INVALID_INPUT","工具参数嵌套过深");if(Array.isArray(v))return v.map(x=>sort(x,depth+1));if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([k,x])=>[k,sort(x,depth+1)]));return v;}return JSON.stringify(sort(value));
}
type Pending={id:string;context:ToolContext;call:ToolCall;hash:string;signal:AbortSignal;abort:()=>void;resolve:(decision:ApprovalDecision)=>void;reject:(error:AppError)=>void};
export class ApprovalService {
  private pending=new Map<string,Pending>();private grants=new Map<string,Pending>();
  constructor(private o:ApprovalOptions){}
  private key(context:ToolContext,call:ToolCall){return JSON.stringify([namespaceKey(context.namespace),context.sessionId,context.runId,call.id]);}
  private hash(context:ToolContext,call:ToolCall){return createHash("sha256").update(JSON.stringify([namespaceKey(context.namespace),context.sessionId,context.runId,call.id,call.name,canonicalArguments(call.arguments)])).digest("hex");}
  private check(context:ToolContext,signal?:AbortSignal){if(namespaceKey(context.namespace)!==namespaceKey(this.o.principal()))throw new AppError("PERMISSION_DENIED","当前身份已失效");if(signal?.aborted)throw new AppError("CANCELLED","操作已取消");const run=this.o.store.runs.get(context.namespace,context.runId);if(run.sessionId!==context.sessionId||!["running","waiting_approval"].includes(run.status))throw new AppError("PERMISSION_DENIED","当前运行不能授权或执行");return run;}
  async request(context:ToolContext,call:ToolCall,view:ApprovalRequestView,signal:AbortSignal):Promise<ApprovalDecision>{
    const run=this.check(context,signal),key=this.key(context,call);if(run.status!=="running"||this.pending.size+this.grants.size>=256||[...this.pending.values()].some(p=>p.context.runId===context.runId))throw new AppError("RUN_ACTIVE","已有待确认操作");const args=canonicalArguments(call.arguments),parsed=approvalRequestSchema.parse({...view,arguments:args});
    if(canonicalArguments(view.arguments)!==args)throw new AppError("PERMISSION_DENIED","展示参数与执行参数不一致");const hash=this.hash(context,call),id=randomUUID();let resolve!:(decision:ApprovalDecision)=>void,reject!:(error:AppError)=>void;const decision=new Promise<ApprovalDecision>((a,b)=>{resolve=a;reject=b;});void decision.catch(()=>{});
    const pending:Pending={id,context:{...context,namespace:{...context.namespace}},call:{...call,arguments:args},hash,signal,resolve,reject,abort:()=>this.revokeRun(context.namespace,context.runId)};this.pending.set(id,pending);
    try {this.o.store.approvals.insert(context.namespace,{view:{...parsed,id,runId:context.runId,callId:call.id,state:"pending"},namespaceKey:namespaceKey(context.namespace),sessionId:context.sessionId,argumentsHash:hash,createdAt:Date.now()});signal.addEventListener("abort",pending.abort,{once:true});if(signal.aborted)pending.abort();this.check(context,signal);
      await this.o.persistEvent(context,{type:"status",status:"waiting_approval"});this.check(context,signal);await this.o.persistEvent(context,{type:"approval_requested",approval:this.o.store.approvals.get(context.namespace,id).view});this.check(context,signal);return await decision;
    }catch(e){this.revokeRun(context.namespace,context.runId);throw e;}finally{if(this.grants.get(key)!==pending)signal.removeEventListener("abort",pending.abort);if(this.pending.get(id)===pending)this.pending.delete(id);}
  }
  consume(context:ToolContext,call:ToolCall):void {const key=this.key(context,call),grant=this.grants.get(key);this.check(context,grant?.signal);if(!grant||grant.hash!==this.hash(context,call))throw new AppError("PERMISSION_DENIED","未取得匹配的单次授权");const record=this.o.store.approvals.get(context.namespace,grant.id);if(record.view.state!=="approved"||record.argumentsHash!==grant.hash)throw new AppError("PERMISSION_DENIED","授权已失效");this.grants.delete(key);grant.signal.removeEventListener("abort",grant.abort);}
  async decide(n:Namespace,id:string,decision:ApprovalDecision):Promise<void>{
    const record=this.o.store.approvals.get(n,id),pending=this.pending.get(id);if(!pending||pending.context.runId!==record.view.runId||pending.context.sessionId!==record.sessionId)throw new AppError("PERMISSION_DENIED","授权已失效");this.check(pending.context,pending.signal);if(namespaceKey(n)!==namespaceKey(pending.context.namespace))throw new AppError("PERMISSION_DENIED","授权归属无效");
    this.o.store.approvals.decide(n,id,decision);try{await this.o.persistEvent(pending.context,{type:"approval_decided",approvalId:id,decision});this.check(pending.context,pending.signal);await this.o.persistEvent(pending.context,{type:"status",status:"running"});this.check(pending.context,pending.signal);if(this.pending.get(id)!==pending)throw new AppError("PERMISSION_DENIED","授权已撤销");if(decision==="approved")this.grants.set(this.key(pending.context,pending.call),pending);pending.resolve(decision);}catch(e){this.grants.delete(this.key(pending.context,pending.call));pending.reject(new AppError("CANCELLED","授权已撤销"));throw e;}
  }
  revokeRun(n:Namespace,runId:string):void {this.o.store.approvals.revokeRun(n,runId);for(const [id,p]of this.pending)if(p.context.runId===runId&&namespaceKey(p.context.namespace)===namespaceKey(n)){this.pending.delete(id);p.signal.removeEventListener("abort",p.abort);p.reject(new AppError("CANCELLED","授权已撤销"));void this.o.persistEvent(p.context,{type:"approval_decided",approvalId:id,decision:"revoked"}).catch(()=>{});}for(const [key,p]of this.grants)if(p.context.runId===runId&&namespaceKey(p.context.namespace)===namespaceKey(n)){this.grants.delete(key);p.signal.removeEventListener("abort",p.abort);}}
}
